const buildNarrative = ({
  company,
  role,
  year,
  platform,
  duration,
  city,
  q1,
  q2,
  incident,
  prepWindow,
  resultLine,
}) => {
  return `I attended the ${company} ${role} process in ${year} through our college placement cell at VRSEC, Vijayawada. The first step was an online assessment on ${platform} with a strict ${duration} timer. I prepared for around ${prepWindow} before the test by solving previous year questions, aptitude sets, and timed coding practice. The test pattern had sections for quantitative aptitude, logical reasoning, verbal, and one coding challenge. My coding question was "${q1}" and I wrote a clean solution after dry-running with sample and edge cases.

After the OA shortlist, I got an interview slot in ${city}. The interviewer asked me to explain my approach for "${q2}" and then changed one condition to check whether I could adapt quickly. I spoke my thought process clearly, compared brute force and optimized approaches, and discussed time/space complexity. I also got questions from DBMS, OOP, OS basics, and project discussion from my final-year mini project. A notable moment was: ${incident}. I stayed calm and asked clarifying questions before answering, which helped me avoid mistakes.

The HR conversation focused on relocation, teamwork, and whether I can work in shifts. I was transparent about strengths and weak areas and gave examples from hackathons and team projects. ${resultLine} The full process took around 10 to 18 days from assessment to final communication, and this experience taught me that consistent timed practice and clear communication matter as much as technical correctness in service-company hiring.`;
};

const buildTips = ({ company, focus }) =>
  `For ${company}, do not ignore basics. Spend 60% time on aptitude + reasoning speed and 40% on coding fundamentals. Practice timed OA sets on HackerRank/HackerEarth, revise OOP, DBMS, OS, and keep one project explanation ready in STAR format. In interview answers, think aloud, state complexity, and verify edge cases before finalizing. ${focus}`;

const batch1 = [
  {
    company: "TCS",
    role: "Ninja Trainee",
    year: 2024,
    roundType: "aptitude",
    offerReceived: true,
    ctcOffered: "3.6 LPA",
    narrative: buildNarrative({
      company: "TCS",
      role: "Ninja Trainee",
      year: 2024,
      platform: "TCS iON",
      duration: "95-minute",
      city: "Vijayawada virtual panel",
      q1: "find second largest without sorting",
      q2: "frequency-based string compression",
      incident:
        "the interviewer intentionally gave an ambiguous input format and watched whether I would confirm constraints instead of assuming",
      prepWindow: "6 weeks",
      resultLine:
        "I received the Ninja offer first, and later got an internal communication about interview feedback being strong on communication.",
    }),
    preparationTips: buildTips({
      company: "TCS",
      focus:
        "Revise percentages, profit-loss, time-work, and series problems because they dominate OA cutoffs.",
    }),
    extractedTags: {
      topics: ["Aptitude", "Quantitative", "Reasoning", "DSA", "Communication"],
      keywords: ["TCS iON", "time-work", "string compression", "complexity", "edge cases"],
      difficulty: 2,
      autoTagged: false,
    },
    embeddingStatus: "pending",
    upvotes: 14,
    isVerified: true,
    views: 88,
  },
  {
    company: "TCS",
    role: "Digital Role",
    year: 2023,
    roundType: "coding",
    offerReceived: false,
    ctcOffered: "",
    narrative: buildNarrative({
      company: "TCS",
      role: "Digital Role",
      year: 2023,
      platform: "CodeVita practice + TCS iON",
      duration: "120-minute",
      city: "Hyderabad panel",
      q1: "matrix border rotation",
      q2: "minimum swaps to group binary values",
      incident:
        "my first approach passed sample tests but failed hidden corner cases, so I quickly rewrote with a safer index-handling strategy",
      prepWindow: "8 weeks",
      resultLine:
        "I cleared Ninja but did not clear Digital, mainly because my second coding problem was partially optimized.",
    }),
    preparationTips: buildTips({
      company: "TCS",
      focus:
        "For Digital, practice medium arrays/matrix questions and explain optimization tradeoffs clearly.",
    }),
    extractedTags: {
      topics: ["DSA", "Matrix", "Arrays", "Algorithms", "Problem Solving"],
      keywords: ["matrix rotation", "minimum swaps", "hidden test cases", "optimization", "CodeVita"],
      difficulty: 3,
      autoTagged: false,
    },
    embeddingStatus: "pending",
    upvotes: 9,
    isVerified: true,
    views: 71,
  },
  {
    company: "TCS",
    role: "Ninja Trainee",
    year: 2024,
    roundType: "aptitude",
    offerReceived: null,
    ctcOffered: "",
    narrative: buildNarrative({
      company: "TCS",
      role: "Ninja Trainee",
      year: 2024,
      platform: "TCS iON",
      duration: "90-minute",
      city: "campus lab, Vijayawada",
      q1: "check balanced parentheses",
      q2: "SQL query for second highest salary",
      incident:
        "network lag happened for 2 minutes during the OA, and the invigilator noted it, so I learned to keep composure under interruptions",
      prepWindow: "5 weeks",
      resultLine:
        "I reached final HR and got positive feedback, but I did not disclose final decision status publicly.",
    }),
    preparationTips: buildTips({
      company: "TCS",
      focus:
        "Keep SQL basics ready: joins, group by, order by, and rank-like queries are frequently asked.",
    }),
    extractedTags: {
      topics: ["Aptitude", "SQL", "Stack", "DBMS", "Verbal"],
      keywords: ["balanced parentheses", "second highest salary", "joins", "TCS iON", "cutoff"],
      difficulty: 2,
      autoTagged: false,
    },
    embeddingStatus: "pending",
    upvotes: 11,
    isVerified: false,
    views: 64,
  },
  {
    company: "TCS",
    role: "Digital Role",
    year: 2022,
    roundType: "coding",
    offerReceived: true,
    ctcOffered: "7.2 LPA",
    narrative: buildNarrative({
      company: "TCS",
      role: "Digital Role",
      year: 2022,
      platform: "TCS iON",
      duration: "110-minute",
      city: "Bengaluru virtual drive",
      q1: "longest subarray with given sum",
      q2: "LRU cache basic operations",
      incident:
        "interviewer asked me to justify hashmap usage over nested loops and expected complexity math before code",
      prepWindow: "9 weeks",
      resultLine:
        "I received the Digital offer after two technical rounds and one HR call.",
    }),
    preparationTips: buildTips({
      company: "TCS",
      focus:
        "Hashing, sliding window, and LRU fundamentals can differentiate Digital from Ninja candidates.",
    }),
    extractedTags: {
      topics: ["DSA", "LRU Cache", "Arrays", "Algorithms", "Data Structures"],
      keywords: ["sliding window", "hashmap", "LRU operations", "time complexity", "Digital round"],
      difficulty: 4,
      autoTagged: false,
    },
    embeddingStatus: "pending",
    upvotes: 22,
    isVerified: true,
    views: 132,
  },
  {
    company: "TCS",
    role: "Ninja Trainee",
    year: 2024,
    roundType: "aptitude",
    offerReceived: true,
    ctcOffered: "3.6 LPA",
    narrative: buildNarrative({
      company: "TCS",
      role: "Ninja Trainee",
      year: 2024,
      platform: "TCS iON",
      duration: "95-minute",
      city: "Vijayawada campus",
      q1: "string palindrome with punctuation ignored",
      q2: "difference between process and thread",
      incident:
        "the interviewer deliberately interrupted mid-answer to test confidence and I politely resumed with structured points",
      prepWindow: "4 weeks",
      resultLine:
        "I accepted the offer because I wanted a stable start and domain transition options.",
    }),
    preparationTips: buildTips({
      company: "TCS",
      focus:
        "Prepare concise OS and OOP definitions with examples; interviewers check clarity more than jargon.",
    }),
    extractedTags: {
      topics: ["Aptitude", "OS", "Strings", "OOP", "Communication"],
      keywords: ["process vs thread", "palindrome", "verbal section", "confidence", "structured answer"],
      difficulty: 1,
      autoTagged: false,
    },
    embeddingStatus: "pending",
    upvotes: 17,
    isVerified: true,
    views: 96,
  },
  {
    company: "TCS",
    role: "Ninja Trainee",
    year: 2023,
    roundType: "coding",
    offerReceived: false,
    ctcOffered: "",
    narrative: buildNarrative({
      company: "TCS",
      role: "Ninja Trainee",
      year: 2023,
      platform: "TCS iON",
      duration: "100-minute",
      city: "remote panel from Vijayawada",
      q1: "remove duplicates from sorted array in-place",
      q2: "binary tree level order traversal explanation",
      incident:
        "I made an off-by-one bug in first submission, caught it by manual trace, and resubmitted in time",
      prepWindow: "5 weeks",
      resultLine:
        "I narrowly missed final shortlist, likely due to lower aptitude sectional score.",
    }),
    preparationTips: buildTips({
      company: "TCS",
      focus:
        "Track sectional timing aggressively; many good coders get filtered by aptitude cutoffs.",
    }),
    extractedTags: {
      topics: ["DSA", "Arrays", "Binary Trees", "Aptitude", "Problem Solving"],
      keywords: ["in-place update", "level order", "off-by-one", "sectional cutoff", "manual trace"],
      difficulty: 2,
      autoTagged: false,
    },
    embeddingStatus: "pending",
    upvotes: 8,
    isVerified: true,
    views: 58,
  },
  {
    company: "TCS",
    role: "Digital Role",
    year: 2024,
    roundType: "coding",
    offerReceived: true,
    ctcOffered: "7 LPA",
    narrative: buildNarrative({
      company: "TCS",
      role: "Digital Role",
      year: 2024,
      platform: "TCS iON",
      duration: "120-minute",
      city: "Hyderabad",
      q1: "maximum path sum in binary tree",
      q2: "design a basic URL shortener high-level flow",
      incident:
        "the interviewer appreciated when I wrote test cases before discussing implementation details",
      prepWindow: "10 weeks",
      resultLine:
        "I got selected in Digital after detailed technical discussion and clear project explanations.",
    }),
    preparationTips: buildTips({
      company: "TCS",
      focus:
        "For Digital, add one mini system-design explanation (cache + DB + API flow) to your prep.",
    }),
    extractedTags: {
      topics: ["Binary Trees", "System Design", "API Design", "Algorithms", "DSA"],
      keywords: ["max path sum", "URL shortener", "test cases", "cache", "Digital offer"],
      difficulty: 4,
      autoTagged: false,
    },
    embeddingStatus: "pending",
    upvotes: 19,
    isVerified: true,
    views: 140,
  },
  {
    company: "TCS",
    role: "Ninja Trainee",
    year: 2021,
    roundType: "aptitude",
    offerReceived: null,
    ctcOffered: "",
    narrative: buildNarrative({
      company: "TCS",
      role: "Ninja Trainee",
      year: 2021,
      platform: "TCS iON",
      duration: "90-minute",
      city: "fully virtual due to restrictions",
      q1: "count vowels and consonants in a string",
      q2: "normalization forms in DBMS",
      incident:
        "my mic failed in HR round, so I switched to phone audio without panic and completed the conversation smoothly",
      prepWindow: "3 weeks",
      resultLine:
        "I did not publicly mention final status, but the interview experience was very constructive.",
    }),
    preparationTips: buildTips({
      company: "TCS",
      focus:
        "Keep backup audio and internet options ready for virtual drives; logistics can impact performance.",
    }),
    extractedTags: {
      topics: ["Aptitude", "DBMS", "Strings", "Verbal", "Communication"],
      keywords: ["normalization", "virtual interview", "mic issue", "vowels", "backup plan"],
      difficulty: 1,
      autoTagged: false,
    },
    embeddingStatus: "pending",
    upvotes: 6,
    isVerified: false,
    views: 42,
  },
  {
    company: "TCS",
    role: "Digital Role",
    year: 2023,
    roundType: "coding",
    offerReceived: true,
    ctcOffered: "7.2 LPA",
    narrative: buildNarrative({
      company: "TCS",
      role: "Digital Role",
      year: 2023,
      platform: "TCS iON",
      duration: "115-minute",
      city: "Chennai panel",
      q1: "merge overlapping intervals",
      q2: "thread synchronization basics in Java",
      incident:
        "interviewer gave a follow-up where interval endpoints were unsorted, testing input sanitization",
      prepWindow: "7 weeks",
      resultLine:
        "I converted my Ninja shortlist to Digital after strong performance in coding follow-ups.",
    }),
    preparationTips: buildTips({
      company: "TCS",
      focus:
        "Practice interval, greedy, and sorting-based questions plus Java concurrency basics.",
    }),
    extractedTags: {
      topics: ["DSA", "Sorting", "Java", "Multithreading", "Algorithms"],
      keywords: ["interval merge", "synchronization", "input sanitization", "greedy", "Digital conversion"],
      difficulty: 3,
      autoTagged: false,
    },
    embeddingStatus: "pending",
    upvotes: 16,
    isVerified: true,
    views: 101,
  },
  {
    company: "TCS",
    role: "Ninja Trainee",
    year: 2024,
    roundType: "aptitude",
    offerReceived: true,
    ctcOffered: "3.6 LPA",
    narrative: buildNarrative({
      company: "TCS",
      role: "Ninja Trainee",
      year: 2024,
      platform: "TCS iON",
      duration: "95-minute",
      city: "Vijayawada",
      q1: "find missing number in 1..n",
      q2: "difference between abstract class and interface",
      incident:
        "I had only 6 minutes left for verbal section and used elimination strategy, which saved cutoff",
      prepWindow: "5 weeks",
      resultLine:
        "I accepted the offer and joined onboarding in the next cycle.",
    }),
    preparationTips: buildTips({
      company: "TCS",
      focus:
        "In aptitude, elimination and approximation techniques can save critical minutes.",
    }),
    extractedTags: {
      topics: ["Aptitude", "Quantitative", "OOP", "DSA", "Reasoning"],
      keywords: ["missing number", "interface", "elimination strategy", "sectional timing", "cutoff"],
      difficulty: 2,
      autoTagged: false,
    },
    embeddingStatus: "pending",
    upvotes: 13,
    isVerified: true,
    views: 79,
  },
  {
    company: "TCS",
    role: "Ninja Trainee",
    year: 2022,
    roundType: "coding",
    offerReceived: false,
    ctcOffered: "",
    narrative: buildNarrative({
      company: "TCS",
      role: "Ninja Trainee",
      year: 2022,
      platform: "HackerRank proctored",
      duration: "90-minute",
      city: "remote",
      q1: "reverse linked list in groups of k",
      q2: "SQL joins on student-course schema",
      incident:
        "I over-optimized too early and lost time; interviewer advised starting with a working baseline first",
      prepWindow: "6 weeks",
      resultLine:
        "I was rejected after technical round, but feedback helped me in later drives.",
    }),
    preparationTips: buildTips({
      company: "TCS",
      focus:
        "Always deliver a correct baseline first, then optimize with interviewer guidance.",
    }),
    extractedTags: {
      topics: ["Linked Lists", "SQL", "DBMS", "Algorithms", "Problem Solving"],
      keywords: ["k-group reverse", "inner join", "baseline solution", "optimization", "HackerRank"],
      difficulty: 3,
      autoTagged: false,
    },
    embeddingStatus: "pending",
    upvotes: 7,
    isVerified: true,
    views: 66,
  },
  {
    company: "TCS",
    role: "Digital Role",
    year: 2024,
    roundType: "coding",
    offerReceived: true,
    ctcOffered: "7.5 LPA",
    narrative: buildNarrative({
      company: "TCS",
      role: "Digital Role",
      year: 2024,
      platform: "TCS iON",
      duration: "120-minute",
      city: "Bengaluru virtual",
      q1: "shortest path in weighted graph (Dijkstra)",
      q2: "redis cache use-case discussion",
      incident:
        "interviewer asked me to choose between BFS and Dijkstra and explain why weighted edges change the choice",
      prepWindow: "9 weeks",
      resultLine:
        "I received the Digital offer with strong rating in problem solving.",
    }),
    preparationTips: buildTips({
      company: "TCS",
      focus:
        "Know when to use BFS vs Dijkstra vs DP; decision logic matters in interviews.",
    }),
    extractedTags: {
      topics: ["Graphs", "Algorithms", "Redis", "DSA", "Problem Solving"],
      keywords: ["Dijkstra", "weighted graph", "BFS comparison", "cache", "decision logic"],
      difficulty: 4,
      autoTagged: false,
    },
    embeddingStatus: "pending",
    upvotes: 24,
    isVerified: true,
    views: 155,
  },
  {
    company: "TCS",
    role: "Ninja Trainee",
    year: 2023,
    roundType: "aptitude",
    offerReceived: null,
    ctcOffered: "",
    narrative: buildNarrative({
      company: "TCS",
      role: "Ninja Trainee",
      year: 2023,
      platform: "TCS iON",
      duration: "90-minute",
      city: "Vijayawada",
      q1: "anagram check",
      q2: "ACID properties with simple example",
      incident:
        "I initially mixed up consistency and isolation but corrected immediately with transaction example",
      prepWindow: "4 weeks",
      resultLine:
        "I completed all rounds but kept final outcome private.",
    }),
    preparationTips: buildTips({
      company: "TCS",
      focus:
        "Revise DBMS transaction concepts with practical examples from banking or e-commerce.",
    }),
    extractedTags: {
      topics: ["Aptitude", "DBMS", "Strings", "Verbal", "Communication"],
      keywords: ["anagram", "ACID", "transaction", "consistency", "isolation"],
      difficulty: 2,
      autoTagged: false,
    },
    embeddingStatus: "pending",
    upvotes: 10,
    isVerified: false,
    views: 60,
  },
  {
    company: "TCS",
    role: "Ninja Trainee",
    year: 2021,
    roundType: "aptitude",
    offerReceived: false,
    ctcOffered: "",
    narrative: buildNarrative({
      company: "TCS",
      role: "Ninja Trainee",
      year: 2021,
      platform: "TCS iON",
      duration: "85-minute",
      city: "online",
      q1: "prime check for multiple inputs",
      q2: "difference between TCP and UDP",
      incident:
        "I spent too much time on one logical reasoning puzzle and rushed final coding part",
      prepWindow: "3 weeks",
      resultLine:
        "I did not clear the final merit list, mostly because my OA time management was weak.",
    }),
    preparationTips: buildTips({
      company: "TCS",
      focus:
        "Cap each aptitude question with a time limit; skip and return instead of getting stuck.",
    }),
    extractedTags: {
      topics: ["Aptitude", "Reasoning", "Networking", "DSA", "Quantitative"],
      keywords: ["prime check", "TCP UDP", "time management", "logical puzzle", "sectional score"],
      difficulty: 1,
      autoTagged: false,
    },
    embeddingStatus: "pending",
    upvotes: 5,
    isVerified: true,
    views: 37,
  },
  {
    company: "TCS",
    role: "Digital Role",
    year: 2024,
    roundType: "coding",
    offerReceived: true,
    ctcOffered: "7.2 LPA",
    narrative: buildNarrative({
      company: "TCS",
      role: "Digital Role",
      year: 2024,
      platform: "TCS iON",
      duration: "115-minute",
      city: "Pune panel",
      q1: "minimum window substring",
      q2: "design REST API for leave management",
      incident:
        "the panel challenged my API error handling approach and asked for status-code mapping",
      prepWindow: "8 weeks",
      resultLine:
        "I got selected after explaining both algorithm and API design decisions clearly.",
    }),
    preparationTips: buildTips({
      company: "TCS",
      focus:
        "Practice sliding-window strings and basic API design with validation and error codes.",
    }),
    extractedTags: {
      topics: ["Strings", "API Design", "Algorithms", "DSA", "Testing"],
      keywords: ["minimum window", "REST API", "status codes", "validation", "sliding window"],
      difficulty: 4,
      autoTagged: false,
    },
    embeddingStatus: "pending",
    upvotes: 21,
    isVerified: true,
    views: 149,
  },
  {
    company: "TCS",
    role: "Ninja Trainee",
    year: 2022,
    roundType: "aptitude",
    offerReceived: true,
    ctcOffered: "3.5 LPA",
    narrative: buildNarrative({
      company: "TCS",
      role: "Ninja Trainee",
      year: 2022,
      platform: "TCS iON",
      duration: "90-minute",
      city: "Vijayawada campus",
      q1: "count set bits",
      q2: "normalization vs denormalization",
      incident:
        "I used rough-sheet checkpoints every 20 minutes, which prevented last-minute panic",
      prepWindow: "5 weeks",
      resultLine:
        "I received the offer and later moved to digital-learning track internally.",
    }),
    preparationTips: buildTips({
      company: "TCS",
      focus:
        "Use timed mock tests with checkpoints; this improves both speed and accuracy.",
    }),
    extractedTags: {
      topics: ["Aptitude", "Bit Manipulation", "DBMS", "Quantitative", "Reasoning"],
      keywords: ["set bits", "normalization", "mock checkpoints", "accuracy", "cutoff clear"],
      difficulty: 2,
      autoTagged: false,
    },
    embeddingStatus: "pending",
    upvotes: 12,
    isVerified: true,
    views: 85,
  },
  {
    company: "TCS",
    role: "Ninja Trainee",
    year: 2023,
    roundType: "aptitude",
    offerReceived: false,
    ctcOffered: "",
    narrative: buildNarrative({
      company: "TCS",
      role: "Ninja Trainee",
      year: 2023,
      platform: "TCS iON",
      duration: "90-minute",
      city: "remote",
      q1: "fibonacci iterative",
      q2: "difference between compiler and interpreter",
      incident:
        "I answered technicals decently but gave a weak HR response on relocation flexibility",
      prepWindow: "4 weeks",
      resultLine:
        "I was rejected in final HR shortlist, likely due to communication and policy-fit concerns.",
    }),
    preparationTips: buildTips({
      company: "TCS",
      focus:
        "Prepare HR responses on relocation, shifts, and teamwork with practical examples.",
    }),
    extractedTags: {
      topics: ["Aptitude", "C/C++", "OS", "HR", "Communication"],
      keywords: ["fibonacci", "compiler interpreter", "relocation", "HR shortlist", "policy fit"],
      difficulty: 2,
      autoTagged: false,
    },
    embeddingStatus: "pending",
    upvotes: 7,
    isVerified: false,
    views: 53,
  },
  {
    company: "TCS",
    role: "Digital Role",
    year: 2024,
    roundType: "coding",
    offerReceived: true,
    ctcOffered: "7.8 LPA",
    narrative: buildNarrative({
      company: "TCS",
      role: "Digital Role",
      year: 2024,
      platform: "HackerEarth campus drive",
      duration: "105-minute",
      city: "Chennai",
      q1: "top k frequent elements using heap",
      q2: "thread-safe queue design idea",
      incident:
        "I explained why heap beats full sorting for large streams and the interviewer specifically nodded at complexity reasoning",
      prepWindow: "9 weeks",
      resultLine:
        "I got the offer and selected backend training preference.",
    }),
    preparationTips: buildTips({
      company: "TCS",
      focus:
        "Heaps, hashing, and concurrency fundamentals are high-value topics for Digital roles.",
    }),
    extractedTags: {
      topics: ["Heaps", "Data Structures", "Concurrency", "Java", "Algorithms"],
      keywords: ["top k frequent", "heap", "thread-safe queue", "complexity", "HackerEarth"],
      difficulty: 4,
      autoTagged: false,
    },
    embeddingStatus: "pending",
    upvotes: 26,
    isVerified: true,
    views: 176,
  },
  {
    company: "TCS",
    role: "Ninja Trainee",
    year: 2022,
    roundType: "aptitude",
    offerReceived: null,
    ctcOffered: "",
    narrative: buildNarrative({
      company: "TCS",
      role: "Ninja Trainee",
      year: 2022,
      platform: "TCS iON",
      duration: "90-minute",
      city: "Vijayawada",
      q1: "valid parentheses",
      q2: "what is indexing in SQL",
      incident:
        "the panel asked me to teach one concept as if they were first-year students; that tested clarity",
      prepWindow: "5 weeks",
      resultLine:
        "I finished process successfully but chose not to publish final result.",
    }),
    preparationTips: buildTips({
      company: "TCS",
      focus:
        "Practice explaining technical ideas in simple language; communication scores matter in service hiring.",
    }),
    extractedTags: {
      topics: ["Aptitude", "SQL", "Stack", "Communication", "Reasoning"],
      keywords: ["valid parentheses", "indexing", "clarity", "simple explanation", "TCS process"],
      difficulty: 2,
      autoTagged: false,
    },
    embeddingStatus: "pending",
    upvotes: 9,
    isVerified: true,
    views: 69,
  },
  {
    company: "TCS",
    role: "Digital Role",
    year: 2024,
    roundType: "coding",
    offerReceived: false,
    ctcOffered: "",
    narrative: buildNarrative({
      company: "TCS",
      role: "Digital Role",
      year: 2024,
      platform: "TCS iON",
      duration: "120-minute",
      city: "Bengaluru",
      q1: "longest increasing subsequence",
      q2: "cache invalidation strategy discussion",
      incident:
        "I solved LIS with O(n log n) only after hints; interviewer expected that approach upfront",
      prepWindow: "8 weeks",
      resultLine:
        "I did not clear final technical bar for Digital though Ninja eligibility remained.",
    }),
    preparationTips: buildTips({
      company: "TCS",
      focus:
        "For medium-hard DSA, learn both classic DP and optimized variants with proof intuition.",
    }),
    extractedTags: {
      topics: ["Dynamic Programming", "Algorithms", "Redis", "DSA", "System Design"],
      keywords: ["LIS", "O(n log n)", "cache invalidation", "technical bar", "optimization"],
      difficulty: 4,
      autoTagged: false,
    },
    embeddingStatus: "pending",
    upvotes: 15,
    isVerified: true,
    views: 118,
  },
  {
    company: "TCS",
    role: "Ninja Trainee",
    year: 2023,
    roundType: "aptitude",
    offerReceived: true,
    ctcOffered: "3.6 LPA",
    narrative: buildNarrative({
      company: "TCS",
      role: "Ninja Trainee",
      year: 2023,
      platform: "TCS iON",
      duration: "92-minute",
      city: "campus",
      q1: "count words in sentence",
      q2: "deadlock conditions in OS",
      incident:
        "I used my internship bug-fix story in HR, which helped demonstrate practical teamwork",
      prepWindow: "4 weeks",
      resultLine:
        "I received the offer and completed documentation within a week.",
    }),
    preparationTips: buildTips({
      company: "TCS",
      focus:
        "Prepare one teamwork conflict story and one failure story for HR rounds.",
    }),
    extractedTags: {
      topics: ["Aptitude", "OS", "Strings", "HR", "Teamwork"],
      keywords: ["deadlock", "word count", "internship story", "teamwork", "documentation"],
      difficulty: 2,
      autoTagged: false,
    },
    embeddingStatus: "pending",
    upvotes: 12,
    isVerified: true,
    views: 90,
  },
  {
    company: "Infosys",
    role: "Systems Engineer",
    year: 2024,
    roundType: "aptitude",
    offerReceived: true,
    ctcOffered: "3.8 LPA",
    narrative: buildNarrative({
      company: "Infosys",
      role: "Systems Engineer",
      year: 2024,
      platform: "Infosys assessment portal",
      duration: "100-minute",
      city: "Vijayawada",
      q1: "palindrome number check",
      q2: "difference between clustered and non-clustered index",
      incident:
        "the interviewer asked me to compare two SQL query plans verbally, which tested conceptual understanding",
      prepWindow: "5 weeks",
      resultLine:
        "I got selected in the final panel and accepted the Systems Engineer offer.",
    }),
    preparationTips: buildTips({
      company: "Infosys",
      focus:
        "Infosys often mixes aptitude with SQL and OOP basics, so keep both tracks active.",
    }),
    extractedTags: {
      topics: ["Aptitude", "SQL", "DBMS", "Quantitative", "Reasoning"],
      keywords: ["index types", "query plan", "palindrome number", "Infosys portal", "final panel"],
      difficulty: 2,
      autoTagged: false,
    },
    embeddingStatus: "pending",
    upvotes: 13,
    isVerified: true,
    views: 84,
  },
  {
    company: "Infosys",
    role: "Specialist Programmer",
    year: 2023,
    roundType: "coding",
    offerReceived: false,
    ctcOffered: "",
    narrative: buildNarrative({
      company: "Infosys",
      role: "Specialist Programmer",
      year: 2023,
      platform: "HackerRank",
      duration: "120-minute",
      city: "Hyderabad",
      q1: "longest substring without repeating characters",
      q2: "design pattern used in your project",
      incident:
        "I solved both coding questions but struggled in deep OOP follow-up where interviewer asked SOLID principle tradeoffs",
      prepWindow: "8 weeks",
      resultLine:
        "I was moved out after technical panel and did not receive Specialist offer.",
    }),
    preparationTips: buildTips({
      company: "Infosys",
      focus:
        "For Specialist roles, combine DSA with strong OOP + design patterns explanations.",
    }),
    extractedTags: {
      topics: ["Strings", "OOP", "Design Patterns", "Algorithms", "DSA"],
      keywords: ["longest substring", "SOLID", "technical follow-up", "HackerRank", "Specialist Programmer"],
      difficulty: 4,
      autoTagged: false,
    },
    embeddingStatus: "pending",
    upvotes: 18,
    isVerified: true,
    views: 130,
  },
  {
    company: "Infosys",
    role: "Systems Engineer",
    year: 2024,
    roundType: "aptitude",
    offerReceived: null,
    ctcOffered: "",
    narrative: buildNarrative({
      company: "Infosys",
      role: "Systems Engineer",
      year: 2024,
      platform: "Infosys online test",
      duration: "95-minute",
      city: "campus lab",
      q1: "check if two strings are rotations",
      q2: "normal forms in DBMS",
      incident:
        "the proctoring tab froze once, and I resumed quickly without losing flow by keeping rough notes",
      prepWindow: "4 weeks",
      resultLine:
        "I completed interview sequence but chose not to disclose final outcome.",
    }),
    preparationTips: buildTips({
      company: "Infosys",
      focus:
        "Practice string basics and DBMS normalization with real table examples.",
    }),
    extractedTags: {
      topics: ["Aptitude", "Strings", "DBMS", "Verbal", "Reasoning"],
      keywords: ["string rotation", "normal forms", "proctoring freeze", "rough notes", "Infosys test"],
      difficulty: 2,
      autoTagged: false,
    },
    embeddingStatus: "pending",
    upvotes: 8,
    isVerified: false,
    views: 56,
  },
  {
    company: "Infosys",
    role: "Digital Specialist Engineer",
    year: 2022,
    roundType: "coding",
    offerReceived: true,
    ctcOffered: "6.5 LPA",
    narrative: buildNarrative({
      company: "Infosys",
      role: "Digital Specialist Engineer",
      year: 2022,
      platform: "HackerRank",
      duration: "110-minute",
      city: "Bengaluru panel",
      q1: "kth smallest in sorted matrix",
      q2: "REST API pagination and error handling",
      incident:
        "interviewer changed matrix constraints mid-way, and I switched from brute-force to heap-based approach",
      prepWindow: "9 weeks",
      resultLine:
        "I received the digital offer and later got mapped to backend project.",
    }),
    preparationTips: buildTips({
      company: "Infosys",
      focus:
        "Know heap and binary-search-on-answer patterns; they appear in digital role questions.",
    }),
    extractedTags: {
      topics: ["Matrix", "Heaps", "API Design", "Algorithms", "DSA"],
      keywords: ["kth smallest", "pagination", "error handling", "constraint change", "heap approach"],
      difficulty: 4,
      autoTagged: false,
    },
    embeddingStatus: "pending",
    upvotes: 20,
    isVerified: true,
    views: 144,
  },
  {
    company: "Infosys",
    role: "Systems Engineer",
    year: 2024,
    roundType: "aptitude",
    offerReceived: true,
    ctcOffered: "3.9 LPA",
    narrative: buildNarrative({
      company: "Infosys",
      role: "Systems Engineer",
      year: 2024,
      platform: "Infosys assessment portal",
      duration: "100-minute",
      city: "Vijayawada",
      q1: "binary search in sorted array",
      q2: "difference between primary key and unique key",
      incident:
        "I was asked to explain one failed project sprint and what I changed after that",
      prepWindow: "5 weeks",
      resultLine:
        "I got selected and completed pre-onboarding documentation quickly.",
    }),
    preparationTips: buildTips({
      company: "Infosys",
      focus:
        "Revise key DBMS constraints and keep one failure-learning story for HR.",
    }),
    extractedTags: {
      topics: ["Aptitude", "Searching", "DBMS", "Behavioral", "Communication"],
      keywords: ["binary search", "primary key", "unique key", "failure story", "onboarding"],
      difficulty: 2,
      autoTagged: false,
    },
    embeddingStatus: "pending",
    upvotes: 15,
    isVerified: true,
    views: 93,
  },
  {
    company: "Infosys",
    role: "Specialist Programmer",
    year: 2023,
    roundType: "coding",
    offerReceived: false,
    ctcOffered: "",
    narrative: buildNarrative({
      company: "Infosys",
      role: "Specialist Programmer",
      year: 2023,
      platform: "HackerRank",
      duration: "120-minute",
      city: "remote",
      q1: "word ladder shortest transformation",
      q2: "producer-consumer concurrency concept",
      incident:
        "I derived BFS solution but coding got delayed due to edge-case handling for dictionary lookup",
      prepWindow: "7 weeks",
      resultLine:
        "I could not clear final coding threshold for Specialist role.",
    }),
    preparationTips: buildTips({
      company: "Infosys",
      focus:
        "Practice graph BFS templates and write edge-case checklist before coding.",
    }),
    extractedTags: {
      topics: ["Graphs", "BFS", "Concurrency", "Algorithms", "DSA"],
      keywords: ["word ladder", "dictionary lookup", "producer consumer", "edge cases", "coding threshold"],
      difficulty: 4,
      autoTagged: false,
    },
    embeddingStatus: "pending",
    upvotes: 11,
    isVerified: true,
    views: 86,
  },
  {
    company: "Infosys",
    role: "Systems Engineer",
    year: 2021,
    roundType: "aptitude",
    offerReceived: true,
    ctcOffered: "3.6 LPA",
    narrative: buildNarrative({
      company: "Infosys",
      role: "Systems Engineer",
      year: 2021,
      platform: "Infosys online portal",
      duration: "95-minute",
      city: "virtual drive",
      q1: "reverse words in a sentence",
      q2: "OSI layers practical example",
      incident:
        "I was nervous in the first 5 minutes but used a paper outline to structure answers",
      prepWindow: "3 weeks",
      resultLine:
        "I got selected and appreciated for calm communication in interview.",
    }),
    preparationTips: buildTips({
      company: "Infosys",
      focus:
        "Networking basics and communication structure can significantly improve interview ratings.",
    }),
    extractedTags: {
      topics: ["Aptitude", "Networking", "Strings", "Communication", "Verbal"],
      keywords: ["reverse words", "OSI layers", "paper outline", "calm communication", "virtual drive"],
      difficulty: 1,
      autoTagged: false,
    },
    embeddingStatus: "pending",
    upvotes: 10,
    isVerified: true,
    views: 72,
  },
  {
    company: "Infosys",
    role: "Digital Specialist Engineer",
    year: 2024,
    roundType: "coding",
    offerReceived: true,
    ctcOffered: "6.8 LPA",
    narrative: buildNarrative({
      company: "Infosys",
      role: "Digital Specialist Engineer",
      year: 2024,
      platform: "HackerEarth",
      duration: "115-minute",
      city: "Pune panel",
      q1: "minimum spanning tree for network cost",
      q2: "NoSQL vs SQL when scaling user events",
      incident:
        "the interviewer asked me to compare Kruskal vs Prim and defend my data-structure choice",
      prepWindow: "10 weeks",
      resultLine:
        "I got the digital offer after two technical rounds.",
    }),
    preparationTips: buildTips({
      company: "Infosys",
      focus:
        "Graph algorithms plus DB scaling tradeoffs are common in digital specialist interviews.",
    }),
    extractedTags: {
      topics: ["Graphs", "SQL", "MongoDB", "Algorithms", "Data Structures"],
      keywords: ["MST", "Kruskal", "Prim", "NoSQL vs SQL", "scaling events"],
      difficulty: 4,
      autoTagged: false,
    },
    embeddingStatus: "pending",
    upvotes: 23,
    isVerified: true,
    views: 167,
  },
  {
    company: "Infosys",
    role: "Systems Engineer",
    year: 2023,
    roundType: "aptitude",
    offerReceived: false,
    ctcOffered: "",
    narrative: buildNarrative({
      company: "Infosys",
      role: "Systems Engineer",
      year: 2023,
      platform: "Infosys assessment",
      duration: "100-minute",
      city: "Vijayawada",
      q1: "find duplicate in array",
      q2: "what is polymorphism",
      incident:
        "I answered coding quickly but missed verbal accuracy due to hurried reading",
      prepWindow: "4 weeks",
      resultLine:
        "I was not shortlisted after OA despite decent coding score.",
    }),
    preparationTips: buildTips({
      company: "Infosys",
      focus:
        "Do not neglect verbal accuracy; read passages slowly and avoid guesswork.",
    }),
    extractedTags: {
      topics: ["Aptitude", "Arrays", "OOP", "Verbal", "Reasoning"],
      keywords: ["duplicate array", "polymorphism", "verbal accuracy", "OA shortlist", "timed reading"],
      difficulty: 2,
      autoTagged: false,
    },
    embeddingStatus: "pending",
    upvotes: 6,
    isVerified: false,
    views: 49,
  },
  {
    company: "Infosys",
    role: "Systems Engineer",
    year: 2024,
    roundType: "aptitude",
    offerReceived: true,
    ctcOffered: "3.8 LPA",
    narrative: buildNarrative({
      company: "Infosys",
      role: "Systems Engineer",
      year: 2024,
      platform: "Infosys online test",
      duration: "95-minute",
      city: "campus",
      q1: "check armstrong number",
      q2: "transaction isolation levels",
      incident:
        "interviewer asked me to explain isolation levels using an ATM withdrawal example",
      prepWindow: "5 weeks",
      resultLine:
        "I secured the offer and completed all verification rounds.",
    }),
    preparationTips: buildTips({
      company: "Infosys",
      focus:
        "Use practical examples for DBMS concepts; interviewers value applied understanding.",
    }),
    extractedTags: {
      topics: ["Aptitude", "DBMS", "SQL", "Quantitative", "Communication"],
      keywords: ["armstrong", "isolation levels", "ATM example", "verification", "online test"],
      difficulty: 2,
      autoTagged: false,
    },
    embeddingStatus: "pending",
    upvotes: 14,
    isVerified: true,
    views: 97,
  },
  {
    company: "Infosys",
    role: "Specialist Programmer",
    year: 2022,
    roundType: "coding",
    offerReceived: null,
    ctcOffered: "",
    narrative: buildNarrative({
      company: "Infosys",
      role: "Specialist Programmer",
      year: 2022,
      platform: "HackerRank",
      duration: "120-minute",
      city: "Hyderabad",
      q1: "edit distance dynamic programming",
      q2: "singleton and factory pattern use in backend service",
      incident:
        "I got edit distance right but optimization discussion on memory reduction was average",
      prepWindow: "8 weeks",
      resultLine:
        "I kept final result undisclosed, but interview depth was clearly above systems-engineer level.",
    }),
    preparationTips: buildTips({
      company: "Infosys",
      focus:
        "Prepare DP state transitions and design-pattern use cases from your own project code.",
    }),
    extractedTags: {
      topics: ["Dynamic Programming", "Design Patterns", "Java", "Algorithms", "Problem Solving"],
      keywords: ["edit distance", "memory optimization", "singleton", "factory", "backend service"],
      difficulty: 4,
      autoTagged: false,
    },
    embeddingStatus: "pending",
    upvotes: 17,
    isVerified: true,
    views: 111,
  },
  {
    company: "Infosys",
    role: "Systems Engineer",
    year: 2023,
    roundType: "aptitude",
    offerReceived: true,
    ctcOffered: "3.7 LPA",
    narrative: buildNarrative({
      company: "Infosys",
      role: "Systems Engineer",
      year: 2023,
      platform: "Infosys portal",
      duration: "100-minute",
      city: "Vijayawada",
      q1: "find first non-repeating character",
      q2: "difference between stack and queue",
      incident:
        "I asked one clarifying question before coding and interviewer appreciated that discipline",
      prepWindow: "4 weeks",
      resultLine:
        "I got the offer and joined in the next onboarding wave.",
    }),
    preparationTips: buildTips({
      company: "Infosys",
      focus:
        "Clarify constraints before coding; that reduces rework and improves interviewer trust.",
    }),
    extractedTags: {
      topics: ["Aptitude", "Strings", "Stack", "Queue", "Data Structures"],
      keywords: ["non-repeating char", "stack queue", "clarifying question", "discipline", "onboarding wave"],
      difficulty: 2,
      autoTagged: false,
    },
    embeddingStatus: "pending",
    upvotes: 12,
    isVerified: true,
    views: 81,
  },
  {
    company: "Infosys",
    role: "Digital Specialist Engineer",
    year: 2024,
    roundType: "coding",
    offerReceived: true,
    ctcOffered: "6.9 LPA",
    narrative: buildNarrative({
      company: "Infosys",
      role: "Digital Specialist Engineer",
      year: 2024,
      platform: "HackerEarth",
      duration: "110-minute",
      city: "Chennai",
      q1: "topological sort for course schedule",
      q2: "basic microservice communication with retries",
      incident:
        "the panel asked how I would avoid cascading failures and I proposed timeout + retry with backoff",
      prepWindow: "9 weeks",
      resultLine:
        "I was selected with positive comments on system-thinking approach.",
    }),
    preparationTips: buildTips({
      company: "Infosys",
      focus:
        "For digital roles, pair graph problems with practical backend resilience concepts.",
    }),
    extractedTags: {
      topics: ["Graphs", "System Design", "Distributed Systems", "Algorithms", "API Design"],
      keywords: ["topological sort", "retries", "backoff", "cascading failure", "microservice"],
      difficulty: 4,
      autoTagged: false,
    },
    embeddingStatus: "pending",
    upvotes: 25,
    isVerified: true,
    views: 172,
  },
  {
    company: "Infosys",
    role: "Systems Engineer",
    year: 2022,
    roundType: "aptitude",
    offerReceived: false,
    ctcOffered: "",
    narrative: buildNarrative({
      company: "Infosys",
      role: "Systems Engineer",
      year: 2022,
      platform: "Infosys test",
      duration: "95-minute",
      city: "remote",
      q1: "rotate array by k",
      q2: "difference between process and thread",
      incident:
        "I answered technicals okay but got stuck in one difficult reasoning grid puzzle for too long",
      prepWindow: "4 weeks",
      resultLine:
        "I was not shortlisted in final OA merit list.",
    }),
    preparationTips: buildTips({
      company: "Infosys",
      focus:
        "Skip hard reasoning puzzles quickly and return later to maximize total score.",
    }),
    extractedTags: {
      topics: ["Aptitude", "Arrays", "OS", "Reasoning", "Quantitative"],
      keywords: ["array rotation", "process thread", "grid puzzle", "merit list", "time allocation"],
      difficulty: 2,
      autoTagged: false,
    },
    embeddingStatus: "pending",
    upvotes: 7,
    isVerified: true,
    views: 57,
  },
  {
    company: "Infosys",
    role: "Systems Engineer",
    year: 2024,
    roundType: "aptitude",
    offerReceived: true,
    ctcOffered: "3.8 LPA",
    narrative: buildNarrative({
      company: "Infosys",
      role: "Systems Engineer",
      year: 2024,
      platform: "Infosys assessment portal",
      duration: "100-minute",
      city: "Vijayawada",
      q1: "valid anagram check",
      q2: "BCNF with simple schema",
      incident:
        "interviewer asked me to teach BCNF in 2 minutes; I used a hostel-room allocation example",
      prepWindow: "5 weeks",
      resultLine:
        "I received offer and later got location preference form.",
    }),
    preparationTips: buildTips({
      company: "Infosys",
      focus:
        "Practice giving 2-minute crisp explanations for DBMS and OOP topics.",
    }),
    extractedTags: {
      topics: ["Aptitude", "DBMS", "Strings", "Communication", "Verbal"],
      keywords: ["anagram", "BCNF", "schema", "2-minute explanation", "location preference"],
      difficulty: 2,
      autoTagged: false,
    },
    embeddingStatus: "pending",
    upvotes: 16,
    isVerified: true,
    views: 104,
  },
  {
    company: "Infosys",
    role: "Specialist Programmer",
    year: 2023,
    roundType: "coding",
    offerReceived: false,
    ctcOffered: "",
    narrative: buildNarrative({
      company: "Infosys",
      role: "Specialist Programmer",
      year: 2023,
      platform: "HackerRank",
      duration: "120-minute",
      city: "Bengaluru",
      q1: "minimum cost to connect ropes",
      q2: "design cache with TTL support",
      incident:
        "I solved coding but gave shallow explanation on cache eviction strategy and stale data handling",
      prepWindow: "8 weeks",
      resultLine:
        "I was rejected in final technical panel for Specialist track.",
    }),
    preparationTips: buildTips({
      company: "Infosys",
      focus:
        "For specialist interviews, include tradeoffs: eviction policy, stale reads, and complexity.",
    }),
    extractedTags: {
      topics: ["Heaps", "Redis", "System Design", "Algorithms", "DSA"],
      keywords: ["connect ropes", "TTL cache", "eviction policy", "stale data", "technical panel"],
      difficulty: 4,
      autoTagged: false,
    },
    embeddingStatus: "pending",
    upvotes: 10,
    isVerified: false,
    views: 75,
  },
  {
    company: "Infosys",
    role: "Systems Engineer",
    year: 2021,
    roundType: "aptitude",
    offerReceived: null,
    ctcOffered: "",
    narrative: buildNarrative({
      company: "Infosys",
      role: "Systems Engineer",
      year: 2021,
      platform: "Infosys virtual assessment",
      duration: "90-minute",
      city: "online",
      q1: "decimal to binary conversion",
      q2: "difference between HTTP and HTTPS",
      incident:
        "I had power fluctuation at home and used mobile hotspot backup immediately",
      prepWindow: "3 weeks",
      resultLine:
        "I completed process but did not share final status publicly.",
    }),
    preparationTips: buildTips({
      company: "Infosys",
      focus:
        "For remote drives, always keep backup power and internet to avoid panic.",
    }),
    extractedTags: {
      topics: ["Aptitude", "Networking", "Bit Manipulation", "Communication", "Reasoning"],
      keywords: ["decimal binary", "HTTP HTTPS", "hotspot backup", "virtual assessment", "stability"],
      difficulty: 1,
      autoTagged: false,
    },
    embeddingStatus: "pending",
    upvotes: 6,
    isVerified: true,
    views: 40,
  },
  {
    company: "Infosys",
    role: "Digital Specialist Engineer",
    year: 2024,
    roundType: "coding",
    offerReceived: true,
    ctcOffered: "7 LPA",
    narrative: buildNarrative({
      company: "Infosys",
      role: "Digital Specialist Engineer",
      year: 2024,
      platform: "HackerEarth",
      duration: "115-minute",
      city: "Hyderabad",
      q1: "LRU cache implementation",
      q2: "rate limiter design for API gateway",
      incident:
        "the interviewer liked that I discussed token bucket and leaky bucket with pros/cons",
      prepWindow: "10 weeks",
      resultLine:
        "I got selected and preferred backend + API engineering role.",
    }),
    preparationTips: buildTips({
      company: "Infosys",
      focus:
        "Master LRU, rate limiting, and concurrency-safe data structures for digital tracks.",
    }),
    extractedTags: {
      topics: ["LRU Cache", "API Design", "Concurrency", "System Design", "Data Structures"],
      keywords: ["token bucket", "leaky bucket", "API gateway", "LRU implementation", "backend role"],
      difficulty: 4,
      autoTagged: false,
    },
    embeddingStatus: "pending",
    upvotes: 27,
    isVerified: true,
    views: 181,
  },
  {
    company: "Infosys",
    role: "Systems Engineer",
    year: 2022,
    roundType: "aptitude",
    offerReceived: true,
    ctcOffered: "3.7 LPA",
    narrative: buildNarrative({
      company: "Infosys",
      role: "Systems Engineer",
      year: 2022,
      platform: "Infosys OA",
      duration: "95-minute",
      city: "Vijayawada",
      q1: "common elements of two arrays",
      q2: "class vs object with real-world example",
      incident:
        "I used a practical cricket-team analogy for OOP and interviewer appreciated relatable explanation",
      prepWindow: "4 weeks",
      resultLine:
        "I received offer and completed joining formalities without delay.",
    }),
    preparationTips: buildTips({
      company: "Infosys",
      focus:
        "Relatable analogies improve OOP answers and interviewer engagement.",
    }),
    extractedTags: {
      topics: ["Aptitude", "Arrays", "OOP", "Communication", "Quantitative"],
      keywords: ["common elements", "class object", "analogy", "joining formalities", "OA"],
      difficulty: 2,
      autoTagged: false,
    },
    embeddingStatus: "pending",
    upvotes: 13,
    isVerified: true,
    views: 89,
  },
  {
    company: "Infosys",
    role: "Systems Engineer",
    year: 2023,
    roundType: "coding",
    offerReceived: false,
    ctcOffered: "",
    narrative: buildNarrative({
      company: "Infosys",
      role: "Systems Engineer",
      year: 2023,
      platform: "HackerRank",
      duration: "90-minute",
      city: "remote",
      q1: "valid sudoku checker",
      q2: "basic transaction handling in SQL",
      incident:
        "I completed checker logic but forgot one 3x3 block edge case initially",
      prepWindow: "5 weeks",
      resultLine:
        "I did not clear coding cutoff this time and focused on fundamentals afterward.",
    }),
    preparationTips: buildTips({
      company: "Infosys",
      focus:
        "Always keep an edge-case checklist for matrix/validation problems.",
    }),
    extractedTags: {
      topics: ["Matrix", "SQL", "DBMS", "Algorithms", "Problem Solving"],
      keywords: ["sudoku checker", "3x3 block", "transaction handling", "coding cutoff", "edge-case checklist"],
      difficulty: 3,
      autoTagged: false,
    },
    embeddingStatus: "pending",
    upvotes: 8,
    isVerified: true,
    views: 67,
  },
  {
    company: "Infosys",
    role: "Systems Engineer",
    year: 2024,
    roundType: "aptitude",
    offerReceived: true,
    ctcOffered: "3.8 LPA",
    narrative: buildNarrative({
      company: "Infosys",
      role: "Systems Engineer",
      year: 2024,
      platform: "Infosys portal",
      duration: "100-minute",
      city: "Vijayawada",
      q1: "check balanced brackets",
      q2: "indexes and query performance",
      incident:
        "I connected SQL indexing concept to my mini-project MongoDB query tuning discussion",
      prepWindow: "6 weeks",
      resultLine:
        "I got selected and received offer mail within one week.",
    }),
    preparationTips: buildTips({
      company: "Infosys",
      focus:
        "Link theory answers with your project examples; it makes responses credible.",
    }),
    extractedTags: {
      topics: ["Aptitude", "SQL", "Stack", "DBMS", "Project Management"],
      keywords: ["balanced brackets", "query performance", "indexing", "project linkage", "offer mail"],
      difficulty: 2,
      autoTagged: false,
    },
    embeddingStatus: "pending",
    upvotes: 15,
    isVerified: true,
    views: 98,
  },
  {
    company: "Wipro",
    role: "Project Engineer",
    year: 2024,
    roundType: "aptitude",
    offerReceived: true,
    ctcOffered: "3.5 LPA",
    narrative: buildNarrative({
      company: "Wipro",
      role: "Project Engineer",
      year: 2024,
      platform: "Wipro National Talent Hunt portal",
      duration: "95-minute",
      city: "Vijayawada",
      q1: "find gcd of two numbers",
      q2: "difference between abstract class and interface in Java",
      incident:
        "I was asked why I chose Java for coding and justified with familiarity plus clean syntax for interviews",
      prepWindow: "4 weeks",
      resultLine:
        "I received the offer and accepted due to early joining timeline.",
    }),
    preparationTips: buildTips({
      company: "Wipro",
      focus:
        "Wipro rounds reward speed in aptitude and clean basics in Java/OOP.",
    }),
    extractedTags: {
      topics: ["Aptitude", "Java", "OOP", "Quantitative", "Reasoning"],
      keywords: ["gcd", "abstract class", "interface", "NTH portal", "joining timeline"],
      difficulty: 2,
      autoTagged: false,
    },
    embeddingStatus: "pending",
    upvotes: 12,
    isVerified: true,
    views: 82,
  },
  {
    company: "Wipro",
    role: "Turbo Role",
    year: 2023,
    roundType: "coding",
    offerReceived: false,
    ctcOffered: "",
    narrative: buildNarrative({
      company: "Wipro",
      role: "Turbo Role",
      year: 2023,
      platform: "HackerRank",
      duration: "110-minute",
      city: "Hyderabad",
      q1: "number of islands in grid",
      q2: "design a simple URL hit counter",
      incident:
        "I solved DFS version but interviewer asked iterative BFS memory tradeoff which I answered partially",
      prepWindow: "7 weeks",
      resultLine:
        "I could not clear Turbo final technical bar, though standard role remained possible.",
    }),
    preparationTips: buildTips({
      company: "Wipro",
      focus:
        "For Turbo, know DFS/BFS tradeoffs and basic system counters with scalability discussion.",
    }),
    extractedTags: {
      topics: ["Graphs", "BFS", "System Design", "Algorithms", "DSA"],
      keywords: ["number of islands", "DFS BFS", "hit counter", "memory tradeoff", "Turbo bar"],
      difficulty: 4,
      autoTagged: false,
    },
    embeddingStatus: "pending",
    upvotes: 14,
    isVerified: true,
    views: 108,
  },
  {
    company: "Wipro",
    role: "Project Engineer",
    year: 2024,
    roundType: "aptitude",
    offerReceived: true,
    ctcOffered: "3.5 LPA",
    narrative: buildNarrative({
      company: "Wipro",
      role: "Project Engineer",
      year: 2024,
      platform: "Wipro assessment",
      duration: "90-minute",
      city: "campus",
      q1: "check leap year",
      q2: "normalization and foreign key",
      incident:
        "HR asked about night-shift readiness and I answered honestly with family discussion context",
      prepWindow: "4 weeks",
      resultLine:
        "I got the offer and completed pre-joining tasks.",
    }),
    preparationTips: buildTips({
      company: "Wipro",
      focus:
        "Prepare HR answers for shift flexibility and relocation with practical clarity.",
    }),
    extractedTags: {
      topics: ["Aptitude", "DBMS", "SQL", "HR", "Communication"],
      keywords: ["leap year", "foreign key", "shift readiness", "relocation", "pre-joining"],
      difficulty: 1,
      autoTagged: false,
    },
    embeddingStatus: "pending",
    upvotes: 11,
    isVerified: true,
    views: 76,
  },
  {
    company: "Wipro",
    role: "Project Engineer",
    year: 2022,
    roundType: "coding",
    offerReceived: null,
    ctcOffered: "",
    narrative: buildNarrative({
      company: "Wipro",
      role: "Project Engineer",
      year: 2022,
      platform: "HackerEarth",
      duration: "95-minute",
      city: "remote",
      q1: "merge two sorted linked lists",
      q2: "difference between GET and POST",
      incident:
        "I forgot null-check once in linked list merge and corrected after interviewer hint",
      prepWindow: "5 weeks",
      resultLine:
        "I finished all rounds but kept final outcome private.",
    }),
    preparationTips: buildTips({
      company: "Wipro",
      focus:
        "Practice linked-list pointer handling and common REST API basics.",
    }),
    extractedTags: {
      topics: ["Linked Lists", "API Design", "DSA", "Java", "Problem Solving"],
      keywords: ["merge lists", "null check", "GET POST", "interviewer hint", "HackerEarth"],
      difficulty: 3,
      autoTagged: false,
    },
    embeddingStatus: "pending",
    upvotes: 9,
    isVerified: false,
    views: 62,
  },
  {
    company: "Wipro",
    role: "Project Engineer",
    year: 2023,
    roundType: "aptitude",
    offerReceived: false,
    ctcOffered: "",
    narrative: buildNarrative({
      company: "Wipro",
      role: "Project Engineer",
      year: 2023,
      platform: "Wipro talent test",
      duration: "90-minute",
      city: "Vijayawada",
      q1: "count digits in integer",
      q2: "deadlock prevention techniques",
      incident:
        "I panicked in verbal section and marked too many guesses, which reduced overall score",
      prepWindow: "3 weeks",
      resultLine:
        "I did not clear OA cutoff in that cycle.",
    }),
    preparationTips: buildTips({
      company: "Wipro",
      focus:
        "Avoid random verbal guesses; accuracy matters more than attempt count.",
    }),
    extractedTags: {
      topics: ["Aptitude", "OS", "Verbal", "Reasoning", "Quantitative"],
      keywords: ["count digits", "deadlock prevention", "verbal guesses", "OA cutoff", "accuracy"],
      difficulty: 1,
      autoTagged: false,
    },
    embeddingStatus: "pending",
    upvotes: 6,
    isVerified: true,
    views: 45,
  },
  {
    company: "Wipro",
    role: "Turbo Role",
    year: 2024,
    roundType: "coding",
    offerReceived: true,
    ctcOffered: "6.5 LPA",
    narrative: buildNarrative({
      company: "Wipro",
      role: "Turbo Role",
      year: 2024,
      platform: "HackerRank",
      duration: "115-minute",
      city: "Bengaluru",
      q1: "minimum operations to make array equal",
      q2: "rate limiter approach for login API",
      incident:
        "I explained token-bucket logic with practical login abuse scenario and interviewer liked depth",
      prepWindow: "8 weeks",
      resultLine:
        "I received Turbo offer after one coding and one technical interview.",
    }),
    preparationTips: buildTips({
      company: "Wipro",
      focus:
        "Practice medium array optimization plus practical API protection concepts.",
    }),
    extractedTags: {
      topics: ["Arrays", "API Design", "Algorithms", "System Design", "Problem Solving"],
      keywords: ["minimum operations", "rate limiter", "token bucket", "login abuse", "Turbo offer"],
      difficulty: 4,
      autoTagged: false,
    },
    embeddingStatus: "pending",
    upvotes: 20,
    isVerified: true,
    views: 138,
  },
  {
    company: "Wipro",
    role: "Project Engineer",
    year: 2021,
    roundType: "aptitude",
    offerReceived: null,
    ctcOffered: "",
    narrative: buildNarrative({
      company: "Wipro",
      role: "Project Engineer",
      year: 2021,
      platform: "Wipro online portal",
      duration: "85-minute",
      city: "online",
      q1: "sum of digits",
      q2: "difference between stack and heap memory",
      incident:
        "my webcam warning popped up twice and I had to reposition quickly while managing time",
      prepWindow: "3 weeks",
      resultLine:
        "I completed all stages but chose not to share final result.",
    }),
    preparationTips: buildTips({
      company: "Wipro",
      focus:
        "Understand memory concepts with examples; they are frequent in entry-level technical rounds.",
    }),
    extractedTags: {
      topics: ["Aptitude", "OS", "Stack", "Reasoning", "Communication"],
      keywords: ["sum digits", "stack heap", "webcam warning", "online portal", "time management"],
      difficulty: 1,
      autoTagged: false,
    },
    embeddingStatus: "pending",
    upvotes: 5,
    isVerified: false,
    views: 39,
  },
  {
    company: "Wipro",
    role: "Project Engineer",
    year: 2024,
    roundType: "coding",
    offerReceived: true,
    ctcOffered: "3.7 LPA",
    narrative: buildNarrative({
      company: "Wipro",
      role: "Project Engineer",
      year: 2024,
      platform: "HackerEarth",
      duration: "95-minute",
      city: "Vijayawada",
      q1: "two sum using hashmap",
      q2: "SQL query with group by and having",
      incident:
        "I first wrote nested loops then optimized to hashmap and explained complexity improvement",
      prepWindow: "6 weeks",
      resultLine:
        "I got selected and accepted as backup while waiting for product-company results.",
    }),
    preparationTips: buildTips({
      company: "Wipro",
      focus:
        "Prepare hashmap classics and SQL aggregation patterns for coding rounds.",
    }),
    extractedTags: {
      topics: ["DSA", "Arrays", "SQL", "Algorithms", "Problem Solving"],
      keywords: ["two sum", "hashmap", "group by", "having", "complexity improvement"],
      difficulty: 3,
      autoTagged: false,
    },
    embeddingStatus: "pending",
    upvotes: 13,
    isVerified: true,
    views: 92,
  },
  {
    company: "Wipro",
    role: "Project Engineer",
    year: 2023,
    roundType: "aptitude",
    offerReceived: false,
    ctcOffered: "",
    narrative: buildNarrative({
      company: "Wipro",
      role: "Project Engineer",
      year: 2023,
      platform: "Wipro talent portal",
      duration: "90-minute",
      city: "campus",
      q1: "string reverse without library",
      q2: "CAP theorem basic understanding",
      incident:
        "I gave textbook CAP definition but failed to give practical tradeoff example when asked",
      prepWindow: "4 weeks",
      resultLine:
        "I was not shortlisted after technical + HR consolidation.",
    }),
    preparationTips: buildTips({
      company: "Wipro",
      focus:
        "For conceptual questions, always attach one practical system example.",
    }),
    extractedTags: {
      topics: ["Aptitude", "Distributed Systems", "Strings", "Behavioral", "Communication"],
      keywords: ["string reverse", "CAP theorem", "tradeoff example", "shortlist", "consolidation"],
      difficulty: 2,
      autoTagged: false,
    },
    embeddingStatus: "pending",
    upvotes: 7,
    isVerified: true,
    views: 55,
  },
  {
    company: "Wipro",
    role: "Turbo Role",
    year: 2022,
    roundType: "coding",
    offerReceived: true,
    ctcOffered: "6.7 LPA",
    narrative: buildNarrative({
      company: "Wipro",
      role: "Turbo Role",
      year: 2022,
      platform: "HackerRank",
      duration: "120-minute",
      city: "Hyderabad",
      q1: "shortest path in unweighted graph",
      q2: "design notification service for campus app",
      incident:
        "I discussed queue-based BFS and then added retry + dead-letter concept for notifications",
      prepWindow: "9 weeks",
      resultLine:
        "I got Turbo offer and joined with backend preference.",
    }),
    preparationTips: buildTips({
      company: "Wipro",
      focus:
        "For Turbo roles, combine DSA with mini system-design thinking.",
    }),
    extractedTags: {
      topics: ["Graphs", "System Design", "API Design", "Algorithms", "DSA"],
      keywords: ["unweighted shortest path", "BFS queue", "notification service", "retry", "dead letter"],
      difficulty: 4,
      autoTagged: false,
    },
    embeddingStatus: "pending",
    upvotes: 21,
    isVerified: true,
    views: 146,
  },
];

export default batch1;
