const buildNarrativeBatch2 = ({
  company,
  role,
  year,
  city,
  oaPlatform,
  techFocus,
  question1,
  question2,
  hrMoment,
  outcomeLine,
}) => `I attended the ${company} ${role} placement process in ${year} through our VRSEC placement cell. This was part of the regular campus drive flow and the first stage was an online test on ${oaPlatform}. The test had aptitude, reasoning, verbal, and one coding/problem-solving section. I prepared for almost a month with timed mock tests and previous drive patterns, because in service-company hiring, consistency and speed matter a lot. After clearing the test, I got shortlisted for interview rounds conducted in ${city}.

The technical round started with my project discussion and then moved to fundamentals. The interviewer focused on ${techFocus} and asked me two detailed questions: "${question1}" and "${question2}". I explained both brute-force and optimized approaches, then discussed time complexity and edge cases before finalizing my answer. They also checked DBMS basics, OOP concepts, OS process-thread differences, and a few scenario-based questions to test practical understanding. I noticed they were more interested in clarity and structured thinking than memorized jargon.

In the HR round, they asked about relocation, shift flexibility, teamwork conflicts, and why I wanted to join ${company}. A key moment was ${hrMoment}. I stayed honest, gave examples from my internship and college team projects, and avoided over-claiming. ${outcomeLine} Overall, this process taught me that for these companies, strong basics plus calm communication plus clean explanations are enough to perform well, even if the questions are not very advanced like top product-company interviews.`;

const buildTipsBatch2 = ({ company, focus }) =>
  `For ${company}, keep prep practical: 50% aptitude/reasoning speed, 30% CS fundamentals (OOP, DBMS, OS, SQL), and 20% coding patterns (arrays, strings, hashing, basic trees). Practice speaking your thought process clearly during mock interviews. Keep 2 HR stories ready: teamwork conflict and failure-learning. ${focus}`;

const mk = (s, idx) => ({
  company: s.company,
  role: s.role,
  year: s.year,
  roundType: s.roundType,
  offerReceived: s.offerReceived,
  ctcOffered: s.offerReceived ? s.ctcOffered : '',
  narrative: buildNarrativeBatch2({
    company: s.company,
    role: s.role,
    year: s.year,
    city: s.city,
    oaPlatform: s.oaPlatform,
    techFocus: s.techFocus,
    question1: s.question1,
    question2: s.question2,
    hrMoment: s.hrMoment,
    outcomeLine: s.outcomeLine,
  }),
  preparationTips: buildTipsBatch2({ company: s.company, focus: s.tipFocus }),
  extractedTags: {
    topics: s.topics,
    keywords: s.keywords,
    difficulty: s.difficulty,
    autoTagged: false,
  },
  embeddingStatus: 'pending',
  upvotes: 6 + (idx % 25),
  isVerified: idx % 10 < 7,
  views: 35 + ((idx * 7) % 160),
});

const batch2Specs = [
  { company: 'TCS', role: 'Ninja Trainee', year: 2024, roundType: 'technical', offerReceived: true, ctcOffered: '3.6 LPA', city: 'Vijayawada', oaPlatform: 'TCS iON', techFocus: 'OOP, DBMS, and SQL joins', question1: 'difference between interface and abstract class with example', question2: 'write SQL for third highest salary', hrMoment: 'I was asked if I can relocate immediately and I gave a clear yes with location flexibility', outcomeLine: 'I received the offer after final HR clearance.', tipFocus: 'Revise SQL joins, group by, and normalization before interview week.', topics: ['Technical', 'OOP', 'DBMS', 'SQL', 'Communication'], keywords: ['interface', 'abstract class', 'third highest salary', 'normalization', 'relocation'], difficulty: 2 },
  { company: 'TCS', role: 'Digital Role', year: 2024, roundType: 'technical', offerReceived: true, ctcOffered: '7.2 LPA', city: 'Hyderabad', oaPlatform: 'TCS iON', techFocus: 'DSA medium patterns and API basics', question1: 'implement LRU cache operations', question2: 'design a simple leave-management API', hrMoment: 'the interviewer challenged one assumption and I calmly corrected my approach', outcomeLine: 'I converted the shortlist into a Digital offer.', tipFocus: 'Practice LRU, sliding window, and basic REST status-code design.', topics: ['DSA', 'LRU Cache', 'API Design', 'SQL', 'Technical'], keywords: ['LRU', 'REST API', 'status code', 'hashmap', 'optimization'], difficulty: 4 },
  { company: 'TCS', role: 'Ninja Trainee', year: 2023, roundType: 'hr', offerReceived: false, ctcOffered: '3.6 LPA', city: 'Chennai virtual panel', oaPlatform: 'TCS iON', techFocus: 'basic CS revision and project explanation', question1: 'explain your mini-project architecture', question2: 'difference between process and thread', hrMoment: 'I gave a weak answer on long-term goals and that likely impacted rating', outcomeLine: 'I did not make the final HR shortlist.', tipFocus: 'Prepare a clear 60-second self-intro and 5-year goal answer.', topics: ['HR', 'Behavioral', 'Communication', 'OS', 'Teamwork'], keywords: ['self introduction', 'career goals', 'process thread', 'project explanation', 'HR shortlist'], difficulty: 2 },
  { company: 'TCS', role: 'Ninja Trainee', year: 2022, roundType: 'technical', offerReceived: null, ctcOffered: '3.5 LPA', city: 'Bengaluru', oaPlatform: 'TCS iON', techFocus: 'arrays, strings, and DBMS transactions', question1: 'find first non-repeating character', question2: 'ACID properties with banking example', hrMoment: 'I was asked about shift timings and answered with practical constraints and willingness', outcomeLine: 'I completed all rounds but chose not to disclose final result.', tipFocus: 'Use practical examples for ACID and transaction isolation.', topics: ['Strings', 'DBMS', 'Technical', 'Aptitude', 'Communication'], keywords: ['non-repeating', 'ACID', 'isolation', 'shift timings', 'banking example'], difficulty: 2 },
  { company: 'TCS', role: 'Digital Role', year: 2024, roundType: 'technical', offerReceived: true, ctcOffered: '7.8 LPA', city: 'Pune', oaPlatform: 'HackerEarth', techFocus: 'graph traversal and system basics', question1: 'Dijkstra shortest path with constraints', question2: 'when to use Redis cache in an app', hrMoment: 'HR asked about handling deadlines and I gave an internship incident with metrics', outcomeLine: 'I got the Digital offer after two discussions.', tipFocus: 'Know BFS vs Dijkstra decision criteria and caching tradeoffs.', topics: ['Graphs', 'Redis', 'Algorithms', 'Technical', 'Problem Solving'], keywords: ['Dijkstra', 'BFS', 'Redis cache', 'deadline handling', 'tradeoff'], difficulty: 4 },
  { company: 'TCS', role: 'Ninja Trainee', year: 2024, roundType: 'hr', offerReceived: true, ctcOffered: '3.6 LPA', city: 'Vijayawada', oaPlatform: 'TCS iON', techFocus: 'project communication and teamwork', question1: 'explain one bug you fixed in project', question2: 'how do you prioritize tasks under pressure', hrMoment: 'I admitted one past mistake and described what I changed in workflow', outcomeLine: 'Offer was released within a week.', tipFocus: 'Use STAR format for conflict and failure stories.', topics: ['HR', 'Behavioral', 'Teamwork', 'Communication', 'Project Management'], keywords: ['STAR', 'team conflict', 'deadline', 'bug fix', 'workflow'], difficulty: 2 },
  { company: 'TCS', role: 'Digital Role', year: 2023, roundType: 'technical', offerReceived: false, ctcOffered: '7.2 LPA', city: 'Hyderabad', oaPlatform: 'TCS iON', techFocus: 'dynamic programming and SQL optimization', question1: 'longest increasing subsequence', question2: 'difference between clustered and non-clustered index', hrMoment: 'I handled technical questions well but appeared rushed in communication', outcomeLine: 'I missed the final bar for Digital.', tipFocus: 'Practice explaining DP state transitions in simple terms.', topics: ['Dynamic Programming', 'SQL', 'DBMS', 'Technical', 'Algorithms'], keywords: ['LIS', 'indexing', 'state transition', 'time complexity', 'digital bar'], difficulty: 4 },
  { company: 'TCS', role: 'Ninja Trainee', year: 2021, roundType: 'hr', offerReceived: null, ctcOffered: '3.4 LPA', city: 'Virtual', oaPlatform: 'TCS iON', techFocus: 'basic fundamentals and communication', question1: 'difference between stack and queue', question2: 'why should we hire you', hrMoment: 'network issue occurred and I switched to phone audio without panic', outcomeLine: 'I did not publish the final decision.', tipFocus: 'Keep backup internet/audio for virtual HR rounds.', topics: ['HR', 'Communication', 'Behavioral', 'Stack', 'Queue'], keywords: ['why hire me', 'virtual interview', 'audio backup', 'stack queue', 'confidence'], difficulty: 1 },
  { company: 'TCS', role: 'Ninja Trainee', year: 2024, roundType: 'technical', offerReceived: true, ctcOffered: '3.6 LPA', city: 'Vijayawada', oaPlatform: 'TCS iON', techFocus: 'SQL, OOP, and basic coding', question1: 'two-sum using hashmap', question2: 'explain inheritance with Java example', hrMoment: 'interviewer noted my clarity when I compared brute force and optimized code', outcomeLine: 'I was selected and completed onboarding documents.', tipFocus: 'Practice two-sum, anagram, and palindrome-style fundamentals.', topics: ['DSA', 'OOP', 'SQL', 'Technical', 'Java'], keywords: ['two sum', 'hashmap', 'inheritance', 'optimization', 'onboarding'], difficulty: 2 },
  { company: 'TCS', role: 'Digital Role', year: 2022, roundType: 'technical', offerReceived: true, ctcOffered: '7 LPA', city: 'Chennai', oaPlatform: 'HackerRank', techFocus: 'concurrency basics and API reliability', question1: 'thread-safe queue design', question2: 'idempotency in REST APIs', hrMoment: 'I used a payment-retry example to justify idempotency', outcomeLine: 'Digital offer was shared after final approval.', tipFocus: 'Revise synchronization, race condition, and idempotency examples.', topics: ['Concurrency', 'API Design', 'Java', 'Technical', 'System Design'], keywords: ['thread-safe', 'race condition', 'idempotency', 'REST', 'retry'], difficulty: 4 },
  { company: 'TCS', role: 'Ninja Trainee', year: 2023, roundType: 'technical', offerReceived: false, ctcOffered: '3.6 LPA', city: 'Remote', oaPlatform: 'TCS iON', techFocus: 'OS + DBMS fundamentals', question1: 'deadlock conditions and prevention', question2: 'difference between where and having in SQL', hrMoment: 'I over-explained one answer and lost time in later questions', outcomeLine: 'I was not selected in final consolidation.', tipFocus: 'Keep answers concise and structured in 3-4 points.', topics: ['OS', 'DBMS', 'SQL', 'Technical', 'Communication'], keywords: ['deadlock', 'where vs having', 'concise answers', 'fundamentals', 'selection'], difficulty: 2 },
  { company: 'TCS', role: 'Ninja Trainee', year: 2024, roundType: 'hr', offerReceived: true, ctcOffered: '3.6 LPA', city: 'Vijayawada', oaPlatform: 'TCS iON', techFocus: 'project accountability and teamwork', question1: 'describe a disagreement in team project', question2: 'how you handled pressure before deadlines', hrMoment: 'I gave a real conflict-resolution example and got positive body-language response', outcomeLine: 'Final mail confirmed selection.', tipFocus: 'Prepare one honest disagreement story with measurable outcome.', topics: ['HR', 'Teamwork', 'Behavioral', 'Communication', 'Leadership'], keywords: ['conflict resolution', 'deadline', 'ownership', 'behavioral', 'final mail'], difficulty: 2 },
  { company: 'TCS', role: 'Digital Role', year: 2024, roundType: 'technical', offerReceived: true, ctcOffered: '7.5 LPA', city: 'Bengaluru', oaPlatform: 'TCS iON', techFocus: 'trees, recursion, and cache patterns', question1: 'maximum depth and diameter of binary tree', question2: 'cache invalidation strategy', hrMoment: 'they asked follow-up constraints and I adjusted complexity accordingly', outcomeLine: 'I received Digital offer and chose backend preference.', tipFocus: 'Practice trees plus recursion dry runs on paper.', topics: ['Binary Trees', 'Recursion', 'Redis', 'Technical', 'Algorithms'], keywords: ['diameter', 'tree depth', 'cache invalidation', 'constraints', 'backend'], difficulty: 4 },
  { company: 'TCS', role: 'Ninja Trainee', year: 2022, roundType: 'hr', offerReceived: true, ctcOffered: '3.5 LPA', city: 'Hyderabad panel', oaPlatform: 'TCS iON', techFocus: 'strengths, weaknesses, and relocation', question1: 'tell me about a failure in college project', question2: 'what motivates you in your first job', hrMoment: 'I avoided generic answers and used concrete project examples', outcomeLine: 'I got selected after HR.', tipFocus: 'Avoid memorized lines; use concrete examples from college projects.', topics: ['HR', 'Behavioral', 'Communication', 'Project Management', 'Teamwork'], keywords: ['strength weakness', 'motivation', 'relocation', 'project failure', 'concrete example'], difficulty: 2 },
  { company: 'TCS', role: 'Ninja Trainee', year: 2023, roundType: 'technical', offerReceived: null, ctcOffered: '3.6 LPA', city: 'Vijayawada', oaPlatform: 'TCS iON', techFocus: 'basic coding plus SQL', question1: 'valid parentheses using stack', question2: 'normalize student-course schema', hrMoment: 'I clarified assumptions before coding and interviewer appreciated discipline', outcomeLine: 'I kept final outcome private.', tipFocus: 'Clarifying input constraints gives strong interviewer signal.', topics: ['Stack', 'SQL', 'DBMS', 'Technical', 'DSA'], keywords: ['valid parentheses', 'normalization', 'constraints', 'stack', 'schema'], difficulty: 2 },
  { company: 'TCS', role: 'Digital Role', year: 2024, roundType: 'technical', offerReceived: false, ctcOffered: '7.2 LPA', city: 'Pune', oaPlatform: 'HackerEarth', techFocus: 'heaps and streaming data', question1: 'top-k frequent elements', question2: 'design log aggregation flow', hrMoment: 'I solved coding but architecture explanation lacked depth on failure handling', outcomeLine: 'Digital final round was not cleared.', tipFocus: 'Add retry, queue, and failure-path discussion in system answers.', topics: ['Heaps', 'System Design', 'Algorithms', 'Technical', 'Data Structures'], keywords: ['top k', 'heap', 'log aggregation', 'retry', 'failure handling'], difficulty: 4 },
  { company: 'TCS', role: 'Ninja Trainee', year: 2021, roundType: 'technical', offerReceived: false, ctcOffered: '3.4 LPA', city: 'Virtual', oaPlatform: 'TCS iON', techFocus: 'OS and networking basics', question1: 'difference between TCP and UDP', question2: 'what is context switching', hrMoment: 'I hesitated during one networking question and confidence dropped', outcomeLine: 'I was not shortlisted after technical discussion.', tipFocus: 'Revise OS/networking definitions with one practical example each.', topics: ['Networking', 'OS', 'Technical', 'Communication', 'Aptitude'], keywords: ['TCP', 'UDP', 'context switch', 'virtual panel', 'confidence'], difficulty: 1 },
  { company: 'TCS', role: 'Ninja Trainee', year: 2024, roundType: 'hr', offerReceived: true, ctcOffered: '3.6 LPA', city: 'Vijayawada', oaPlatform: 'TCS iON', techFocus: 'culture fit and consistency', question1: 'how do you work in teams with different opinions', question2: 'why TCS over other offers', hrMoment: 'I explained stability plus learning path as my reason', outcomeLine: 'Offer confirmed and I accepted.', tipFocus: 'Prepare honest reason for choosing company, not generic lines.', topics: ['HR', 'Behavioral', 'Communication', 'Teamwork', 'Leadership'], keywords: ['culture fit', 'team opinions', 'why TCS', 'offer accept', 'learning path'], difficulty: 2 },
  { company: 'TCS', role: 'Digital Role', year: 2023, roundType: 'technical', offerReceived: true, ctcOffered: '7.1 LPA', city: 'Chennai', oaPlatform: 'TCS iON', techFocus: 'DP plus OOP design', question1: 'coin change minimum coins', question2: 'design class model for library system', hrMoment: 'they asked me to justify class responsibilities and I handled it well', outcomeLine: 'I received Digital offer after final review.', tipFocus: 'Practice DP and small LLD class diagrams for interviews.', topics: ['Dynamic Programming', 'LLD', 'OOP', 'Technical', 'Algorithms'], keywords: ['coin change', 'class design', 'LLD', 'responsibility', 'digital'], difficulty: 3 },
  { company: 'TCS', role: 'Ninja Trainee', year: 2022, roundType: 'hr', offerReceived: null, ctcOffered: '3.5 LPA', city: 'Remote', oaPlatform: 'TCS iON', techFocus: 'behavior and communication', question1: 'how do you handle criticism', question2: 'describe one team project challenge', hrMoment: 'I acknowledged one mistake openly and showed corrective steps', outcomeLine: 'I did not publish final result status.', tipFocus: 'In HR, humility plus clear corrective action creates trust.', topics: ['HR', 'Behavioral', 'Communication', 'Teamwork', 'Project Management'], keywords: ['criticism', 'challenge', 'corrective action', 'humility', 'trust'], difficulty: 2 },

  { company: 'Infosys', role: 'Systems Engineer', year: 2024, roundType: 'technical', offerReceived: true, ctcOffered: '3.8 LPA', city: 'Vijayawada', oaPlatform: 'Infosys Assessment Portal', techFocus: 'SQL queries, OOP, and OS basics', question1: 'difference between join types with examples', question2: 'what is polymorphism in real project context', hrMoment: 'HR asked relocation question and I gave flexible preference list', outcomeLine: 'I received Systems Engineer offer.', tipFocus: 'Revise SQL joins and OOP principles with project examples.', topics: ['Technical', 'SQL', 'OOP', 'DBMS', 'OS'], keywords: ['joins', 'polymorphism', 'relocation', 'systems engineer', 'project context'], difficulty: 2 },
  { company: 'Infosys', role: 'Specialist Programmer', year: 2024, roundType: 'technical', offerReceived: false, ctcOffered: '9.5 LPA', city: 'Hyderabad', oaPlatform: 'HackerRank', techFocus: 'graph and string optimization', question1: 'word ladder shortest path', question2: 'design pattern usage in backend APIs', hrMoment: 'I did well in coding but gave weak optimization rationale', outcomeLine: 'Specialist final cut was not cleared.', tipFocus: 'For specialist track, always explain why your approach is optimal.', topics: ['Graphs', 'Strings', 'Design Patterns', 'Technical', 'Algorithms'], keywords: ['word ladder', 'shortest path', 'backend APIs', 'optimization rationale', 'specialist'], difficulty: 4 },
  { company: 'Infosys', role: 'Systems Engineer', year: 2023, roundType: 'hr', offerReceived: true, ctcOffered: '3.7 LPA', city: 'Pune virtual', oaPlatform: 'Infosys Test Portal', techFocus: 'teamwork and communication', question1: 'describe one difficult teammate situation', question2: 'why Infosys and not others', hrMoment: 'I provided a balanced answer on career growth and learning', outcomeLine: 'Final HR was cleared and offer released.', tipFocus: 'Keep 2-3 HR stories ready with measurable outcomes.', topics: ['HR', 'Behavioral', 'Communication', 'Teamwork', 'Leadership'], keywords: ['team conflict', 'career growth', 'why Infosys', 'HR clear', 'learning'], difficulty: 2 },
  { company: 'Infosys', role: 'Digital Specialist Engineer', year: 2022, roundType: 'technical', offerReceived: true, ctcOffered: '6.5 LPA', city: 'Bengaluru', oaPlatform: 'HackerEarth', techFocus: 'MST, arrays, and API behavior', question1: 'minimum spanning tree implementation', question2: 'how to design paginated API', hrMoment: 'interviewer changed constraints and I adapted quickly', outcomeLine: 'I got Digital Specialist offer.', tipFocus: 'Practice graph plus API design combinations for digital tracks.', topics: ['Graphs', 'API Design', 'Algorithms', 'Technical', 'Data Structures'], keywords: ['MST', 'Kruskal', 'pagination', 'constraints', 'digital specialist'], difficulty: 4 },
  { company: 'Infosys', role: 'Systems Engineer', year: 2024, roundType: 'technical', offerReceived: true, ctcOffered: '3.9 LPA', city: 'Vijayawada', oaPlatform: 'Infosys Portal', techFocus: 'DBMS plus SQL performance', question1: 'primary key vs unique key', question2: 'indexing impact on query time', hrMoment: 'I used my mini-project MongoDB indexing comparison as evidence', outcomeLine: 'Offer confirmed in one week.', tipFocus: 'Link database theory answers to your own project work.', topics: ['DBMS', 'SQL', 'Technical', 'MongoDB', 'Communication'], keywords: ['primary key', 'unique key', 'indexing', 'query performance', 'mini project'], difficulty: 2 },
  { company: 'Infosys', role: 'Systems Engineer', year: 2021, roundType: 'hr', offerReceived: null, ctcOffered: '3.6 LPA', city: 'Virtual', oaPlatform: 'Infosys Virtual Assessment', techFocus: 'behavioral readiness and flexibility', question1: 'what are your strengths and weaknesses', question2: 'how do you react to feedback from seniors', hrMoment: 'there was a brief connectivity issue and I resumed calmly', outcomeLine: 'I did not disclose the final status.', tipFocus: 'Practice calm delivery and keep backup network for virtual rounds.', topics: ['HR', 'Behavioral', 'Communication', 'Teamwork', 'Project Management'], keywords: ['strength weakness', 'feedback', 'virtual issue', 'calm delivery', 'flexibility'], difficulty: 1 },
  { company: 'Infosys', role: 'Specialist Programmer', year: 2023, roundType: 'technical', offerReceived: false, ctcOffered: '9.5 LPA', city: 'Chennai', oaPlatform: 'HackerRank', techFocus: 'dynamic programming and concurrency basics', question1: 'edit distance with optimization', question2: 'producer-consumer in Java', hrMoment: 'I solved baseline DP but struggled to justify memory optimization', outcomeLine: 'I was not selected for Specialist this cycle.', tipFocus: 'Practice DP optimization and concurrency patterns with dry runs.', topics: ['Dynamic Programming', 'Java', 'Concurrency', 'Technical', 'Algorithms'], keywords: ['edit distance', 'memory optimization', 'producer consumer', 'baseline', 'specialist'], difficulty: 4 },
  { company: 'Infosys', role: 'Systems Engineer', year: 2024, roundType: 'technical', offerReceived: true, ctcOffered: '3.8 LPA', city: 'Vijayawada', oaPlatform: 'Infosys Assessment', techFocus: 'strings, stacks, and SQL basics', question1: 'balanced brackets validation', question2: 'difference between where and having', hrMoment: 'I asked one clarification before coding and got positive feedback', outcomeLine: 'I got selected after final panel.', tipFocus: 'Small clarification questions help avoid rework in coding rounds.', topics: ['Strings', 'Stack', 'SQL', 'Technical', 'Problem Solving'], keywords: ['balanced brackets', 'where having', 'clarification', 'final panel', 'selection'], difficulty: 2 },
  { company: 'Infosys', role: 'Digital Specialist Engineer', year: 2024, roundType: 'technical', offerReceived: true, ctcOffered: '6.9 LPA', city: 'Hyderabad', oaPlatform: 'HackerEarth', techFocus: 'graph scheduling and resilience', question1: 'topological sort for task scheduling', question2: 'retry with exponential backoff in services', hrMoment: 'I discussed failure scenarios with practical examples', outcomeLine: 'Digital offer received.', tipFocus: 'Always include failure-path handling in architecture answers.', topics: ['Graphs', 'Distributed Systems', 'System Design', 'Technical', 'API Design'], keywords: ['topological sort', 'backoff', 'retry', 'failure scenario', 'resilience'], difficulty: 4 },
  { company: 'Infosys', role: 'Systems Engineer', year: 2022, roundType: 'hr', offerReceived: false, ctcOffered: '3.7 LPA', city: 'Remote', oaPlatform: 'Infosys OA', techFocus: 'culture and communication', question1: 'why should we hire you', question2: 'describe a project failure and recovery', hrMoment: 'my answer on relocation sounded uncertain', outcomeLine: 'I was not selected in HR consolidation.', tipFocus: 'Be clear and confident on relocation and joining timelines.', topics: ['HR', 'Behavioral', 'Communication', 'Project Management', 'Teamwork'], keywords: ['why hire me', 'relocation', 'project failure', 'recovery', 'HR consolidation'], difficulty: 2 },
  { company: 'Infosys', role: 'Systems Engineer', year: 2023, roundType: 'technical', offerReceived: true, ctcOffered: '3.7 LPA', city: 'Vijayawada', oaPlatform: 'Infosys Test Portal', techFocus: 'arrays plus DBMS', question1: 'find duplicate in array efficiently', question2: 'normalization forms with examples', hrMoment: 'I used concise 3-point answers and saved time', outcomeLine: 'Offer rolled out after document verification.', tipFocus: 'Practice concise explanation style for theory topics.', topics: ['Arrays', 'DBMS', 'Technical', 'SQL', 'Aptitude'], keywords: ['duplicate array', 'normalization', 'concise answer', 'verification', 'offer'], difficulty: 2 },
  { company: 'Infosys', role: 'Specialist Programmer', year: 2024, roundType: 'technical', offerReceived: null, ctcOffered: '9.5 LPA', city: 'Bengaluru', oaPlatform: 'HackerRank', techFocus: 'heaps and cache design', question1: 'minimum cost to connect ropes', question2: 'TTL cache design tradeoffs', hrMoment: 'I covered complexity but missed one edge case in eviction logic', outcomeLine: 'I chose not to disclose final decision.', tipFocus: 'For cache design, discuss TTL, eviction, and stale reads explicitly.', topics: ['Heaps', 'Redis', 'System Design', 'Technical', 'Algorithms'], keywords: ['connect ropes', 'TTL cache', 'eviction', 'stale reads', 'edge case'], difficulty: 4 },
  { company: 'Infosys', role: 'Systems Engineer', year: 2021, roundType: 'technical', offerReceived: true, ctcOffered: '3.6 LPA', city: 'Virtual', oaPlatform: 'Infosys Virtual Test', techFocus: 'networking and OS basics', question1: 'HTTP vs HTTPS and TLS overview', question2: 'difference between process and thread', hrMoment: 'I used plain language and interviewer appreciated clarity', outcomeLine: 'I was selected in final list.', tipFocus: 'Use simple analogies for networking and OS concepts.', topics: ['Networking', 'OS', 'Technical', 'Communication', 'Verbal'], keywords: ['HTTP', 'HTTPS', 'TLS', 'process thread', 'clarity'], difficulty: 1 },
  { company: 'Infosys', role: 'Systems Engineer', year: 2024, roundType: 'hr', offerReceived: true, ctcOffered: '3.8 LPA', city: 'Vijayawada', oaPlatform: 'Infosys Assessment Portal', techFocus: 'HR fit and communication', question1: 'how do you balance academics and coding prep', question2: 'what are your immediate career goals', hrMoment: 'I shared weekly schedule and concrete learning targets', outcomeLine: 'I got final HR confirmation.', tipFocus: 'Use concrete routines and measurable goals in HR responses.', topics: ['HR', 'Behavioral', 'Communication', 'Project Management', 'Leadership'], keywords: ['career goals', 'schedule', 'learning targets', 'HR confirmation', 'balance'], difficulty: 2 },
  { company: 'Infosys', role: 'Digital Specialist Engineer', year: 2022, roundType: 'technical', offerReceived: false, ctcOffered: '6.5 LPA', city: 'Hyderabad', oaPlatform: 'HackerEarth', techFocus: 'LRU plus API throttling', question1: 'implement LRU cache with hashmap plus DLL', question2: 'rate limiting for login endpoint', hrMoment: 'I explained token bucket but missed distributed synchronization detail', outcomeLine: 'Digital final bar was not met.', tipFocus: 'When discussing rate limiting, include distributed coordination concerns.', topics: ['LRU Cache', 'API Design', 'Concurrency', 'Technical', 'System Design'], keywords: ['LRU', 'DLL', 'token bucket', 'rate limiter', 'distributed sync'], difficulty: 4 },

  { company: 'Wipro', role: 'Project Engineer', year: 2024, roundType: 'technical', offerReceived: true, ctcOffered: '3.5 LPA', city: 'Vijayawada', oaPlatform: 'Wipro Talent Portal', techFocus: 'Java OOP and SQL fundamentals', question1: 'abstract class vs interface in Java', question2: 'write SQL using group by and having', hrMoment: 'I kept answers short and practical which helped confidence', outcomeLine: 'I received offer after technical plus HR.', tipFocus: 'Revise Java OOP plus SQL aggregations before final interview.', topics: ['Java', 'OOP', 'SQL', 'Technical', 'DBMS'], keywords: ['abstract class', 'interface', 'group by', 'having', 'practical answers'], difficulty: 2 },
  { company: 'Wipro', role: 'Turbo Role', year: 2024, roundType: 'technical', offerReceived: true, ctcOffered: '6.5 LPA', city: 'Bengaluru', oaPlatform: 'HackerRank', techFocus: 'graphs and backend basics', question1: 'number of islands using BFS', question2: 'rate limiter for login API', hrMoment: 'I explained token bucket with real abuse scenario', outcomeLine: 'Turbo offer was released.', tipFocus: 'Practice BFS/DFS plus API protection patterns.', topics: ['Graphs', 'BFS', 'API Design', 'Technical', 'Algorithms'], keywords: ['number of islands', 'token bucket', 'rate limiter', 'abuse scenario', 'turbo'], difficulty: 4 },
  { company: 'Wipro', role: 'Project Engineer', year: 2023, roundType: 'hr', offerReceived: false, ctcOffered: '3.5 LPA', city: 'Hyderabad virtual', oaPlatform: 'Wipro Assessment', techFocus: 'behavioral and role fit', question1: 'why Wipro and your long-term plan', question2: 'how you handle disagreements in team', hrMoment: 'I gave generic responses and could not support them with examples', outcomeLine: 'I was not selected after HR consolidation.', tipFocus: 'Use specific examples for every HR answer; avoid generic statements.', topics: ['HR', 'Behavioral', 'Communication', 'Teamwork', 'Leadership'], keywords: ['why Wipro', 'long-term plan', 'disagreement', 'generic response', 'HR'], difficulty: 2 },
  { company: 'Wipro', role: 'Project Engineer', year: 2022, roundType: 'technical', offerReceived: null, ctcOffered: '3.4 LPA', city: 'Remote', oaPlatform: 'HackerEarth', techFocus: 'linked lists and REST basics', question1: 'merge two sorted linked lists', question2: 'difference between GET and POST', hrMoment: 'I corrected a null-pointer bug during discussion and recovered well', outcomeLine: 'I completed all stages but kept result private.', tipFocus: 'Practice pointer dry-runs for linked list questions.', topics: ['Linked Lists', 'API Design', 'Technical', 'Java', 'Problem Solving'], keywords: ['merge lists', 'null pointer', 'GET POST', 'dry run', 'recovery'], difficulty: 3 },
  { company: 'Wipro', role: 'Project Engineer', year: 2024, roundType: 'hr', offerReceived: true, ctcOffered: '3.5 LPA', city: 'Vijayawada', oaPlatform: 'Wipro Portal', techFocus: 'shift flexibility and communication', question1: 'are you ready for shifts and relocation', question2: 'tell me about one leadership moment', hrMoment: 'I answered honestly and still showed flexibility', outcomeLine: 'I got selected and accepted the offer.', tipFocus: 'Be honest but solution-oriented when discussing constraints.', topics: ['HR', 'Behavioral', 'Communication', 'Leadership', 'Teamwork'], keywords: ['shift', 'relocation', 'leadership moment', 'honesty', 'selected'], difficulty: 1 },
  { company: 'Wipro', role: 'Turbo Role', year: 2023, roundType: 'technical', offerReceived: false, ctcOffered: '6.3 LPA', city: 'Chennai', oaPlatform: 'HackerRank', techFocus: 'arrays and system counters', question1: 'minimum operations to equalize array', question2: 'design URL hit counter', hrMoment: 'I solved coding but did not discuss scale bottlenecks deeply', outcomeLine: 'Turbo final shortlist missed.', tipFocus: 'In system answers, include scaling bottlenecks and storage choice.', topics: ['Arrays', 'System Design', 'Technical', 'Algorithms', 'Data Structures'], keywords: ['minimum operations', 'hit counter', 'scale bottleneck', 'shortlist', 'storage'], difficulty: 4 },
  { company: 'Wipro', role: 'Project Engineer', year: 2021, roundType: 'technical', offerReceived: true, ctcOffered: '3.4 LPA', city: 'Virtual', oaPlatform: 'Wipro Online Test', techFocus: 'OS memory and C basics', question1: 'stack vs heap memory', question2: 'difference between pass by value and reference', hrMoment: 'I used simple examples and stayed calm despite webcam warning', outcomeLine: 'I was selected in final panel.', tipFocus: 'Prepare simple memory examples in C/C++ and Java contexts.', topics: ['OS', 'C/C++', 'Technical', 'Communication', 'Aptitude'], keywords: ['stack heap', 'pass by value', 'webcam warning', 'simple examples', 'panel'], difficulty: 1 },
  { company: 'Wipro', role: 'Project Engineer', year: 2024, roundType: 'technical', offerReceived: true, ctcOffered: '3.7 LPA', city: 'Vijayawada', oaPlatform: 'HackerEarth', techFocus: 'hashing and SQL query writing', question1: 'two sum with hashmap', question2: 'join query for employee-department schema', hrMoment: 'interviewer asked optimization and I compared O(n2) vs O(n)', outcomeLine: 'Offer released after final verification.', tipFocus: 'Hashmap fundamentals are frequently enough for service-company coding rounds.', topics: ['DSA', 'Arrays', 'SQL', 'Technical', 'Algorithms'], keywords: ['two sum', 'hashmap', 'join query', 'O(n)', 'optimization'], difficulty: 3 },
  { company: 'Wipro', role: 'Project Engineer', year: 2023, roundType: 'hr', offerReceived: false, ctcOffered: '3.5 LPA', city: 'Remote', oaPlatform: 'Wipro Talent Test', techFocus: 'behavioral alignment', question1: 'how do you respond to critical feedback', question2: 'why should Wipro choose you', hrMoment: 'I answered quickly but examples were weak and unstructured', outcomeLine: 'I did not clear HR stage.', tipFocus: 'Use STAR method and avoid abstract claims in HR responses.', topics: ['HR', 'Behavioral', 'Communication', 'Teamwork', 'Project Management'], keywords: ['critical feedback', 'why choose you', 'STAR', 'unstructured', 'HR stage'], difficulty: 2 },
  { company: 'Wipro', role: 'Turbo Role', year: 2022, roundType: 'technical', offerReceived: true, ctcOffered: '6.7 LPA', city: 'Hyderabad', oaPlatform: 'HackerRank', techFocus: 'graph shortest paths and async design', question1: 'shortest path in unweighted graph', question2: 'notification service with retry queue', hrMoment: 'I discussed retry plus dead-letter queue clearly', outcomeLine: 'Turbo offer confirmed.', tipFocus: 'Know queue-based retry and dead-letter basics for backend design.', topics: ['Graphs', 'System Design', 'API Design', 'Technical', 'Algorithms'], keywords: ['shortest path', 'retry queue', 'dead-letter', 'notification', 'turbo offer'], difficulty: 4 },
  { company: 'Wipro', role: 'Project Engineer', year: 2024, roundType: 'technical', offerReceived: true, ctcOffered: '3.5 LPA', city: 'Vijayawada', oaPlatform: 'Wipro Portal', techFocus: 'DBMS plus OOP essentials', question1: 'normalization up to 3NF', question2: 'encapsulation with practical example', hrMoment: 'I kept answers grounded in my mini-project implementation', outcomeLine: 'I cleared both technical and HR.', tipFocus: 'Prepare normalization plus OOP examples from your own project code.', topics: ['DBMS', 'OOP', 'Technical', 'SQL', 'Communication'], keywords: ['3NF', 'encapsulation', 'mini project', 'technical clear', 'grounded'], difficulty: 2 },
  { company: 'Wipro', role: 'Project Engineer', year: 2022, roundType: 'hr', offerReceived: null, ctcOffered: '3.4 LPA', city: 'Bengaluru virtual', oaPlatform: 'Wipro Assessment', techFocus: 'career goals and flexibility', question1: 'where do you see yourself in 3 years', question2: 'how do you balance quality and deadlines', hrMoment: 'I gave realistic goals and admitted areas I am improving', outcomeLine: 'I did not share final status publicly.', tipFocus: 'Realistic, honest career goals work better than overconfident claims.', topics: ['HR', 'Behavioral', 'Communication', 'Project Management', 'Leadership'], keywords: ['3 years plan', 'quality vs deadlines', 'realistic goals', 'improvement', 'virtual'], difficulty: 2 },
  { company: 'Wipro', role: 'Turbo Role', year: 2024, roundType: 'technical', offerReceived: false, ctcOffered: '6.5 LPA', city: 'Bengaluru', oaPlatform: 'HackerRank', techFocus: 'DP and backend rate limiting', question1: 'longest increasing subsequence', question2: 'distributed rate limiter design', hrMoment: 'I solved LIS but missed distributed lock discussion', outcomeLine: 'I missed Turbo final technical bar.', tipFocus: 'For distributed systems questions, include synchronization concerns.', topics: ['Dynamic Programming', 'Distributed Systems', 'Technical', 'Algorithms', 'Concurrency'], keywords: ['LIS', 'rate limiter', 'distributed lock', 'technical bar', 'synchronization'], difficulty: 4 },
  { company: 'Wipro', role: 'Project Engineer', year: 2021, roundType: 'technical', offerReceived: true, ctcOffered: '3.4 LPA', city: 'Virtual', oaPlatform: 'Wipro Online', techFocus: 'basic coding, OS, and SQL', question1: 'check leap year and edge cases', question2: 'difference between delete, truncate, and drop', hrMoment: 'I answered in table format verbally which improved clarity', outcomeLine: 'I was selected in final merit list.', tipFocus: 'Use quick comparison tables mentally for DBMS command differences.', topics: ['SQL', 'OS', 'Technical', 'Aptitude', 'Communication'], keywords: ['leap year', 'delete truncate drop', 'edge cases', 'merit list', 'clarity'], difficulty: 1 },
  { company: 'Wipro', role: 'Project Engineer', year: 2023, roundType: 'hr', offerReceived: true, ctcOffered: '3.5 LPA', city: 'Vijayawada', oaPlatform: 'Wipro Talent Test', techFocus: 'behavioral maturity and team fit', question1: 'tell me about a time you led a team task', question2: 'how do you handle repeated failures', hrMoment: 'I shared hackathon failure and recovery with concrete outcomes', outcomeLine: 'HR round cleared and offer released.', tipFocus: 'Keep one failure-recovery story with numbers and outcome.', topics: ['HR', 'Behavioral', 'Leadership', 'Communication', 'Teamwork'], keywords: ['led team', 'failure recovery', 'hackathon', 'outcome', 'HR cleared'], difficulty: 2 },
];

const batch2 = batch2Specs.map((s, i) => mk(s, i));

export default batch2;
