const buildNarrativeBatch3 = ({
  company,
  role,
  year,
  city,
  platform,
  testDuration,
  prepWindow,
  roundType,
  q1,
  q2,
  projectAngle,
  behaviorMoment,
  resultLine,
}) => `I attended the ${company} ${role} placement process in ${year} through our VRSEC placement cell in Vijayawada. The first step was an online assessment on ${platform} with a strict ${testDuration} timer. I prepared for around ${prepWindow} by splitting my schedule into aptitude practice, core CS revision, and timed coding sets. The OA pattern was very service-company oriented: quantitative aptitude, logical reasoning, verbal, and one coding/problem-solving section. My coding/problem section included questions like "${q1}" and "${q2}", and I made sure to dry-run edge cases before submitting. I also tracked sectional timing because these drives often eliminate candidates on speed, not only correctness.

After the OA shortlist, I had interview rounds in ${city}. Since this was a ${roundType} focused round, the panel checked clarity, fundamentals, and practical thinking more than theoretical jargon. They asked me to explain my project with emphasis on ${projectAngle}, then followed up with DBMS, OOP, OS, SQL, and basic debugging scenarios. One useful lesson was that interviewers liked concise, structured answers: first approach, then complexity, then tradeoff. During the discussion, ${behaviorMoment}. That moment actually helped me settle down and communicate better.

In HR/managerial discussion, they asked about relocation, shift readiness, team conflicts, and my learning plan for the first year. I kept answers honest and used concrete examples from hackathons and mini-project work instead of generic lines. ${resultLine} Overall, this experience showed me that for companies like ${company}, strong basics, clean communication, and calm handling of pressure are enough to perform well even without very advanced competitive-programming style preparation.`;

const buildTipsBatch3 = ({ company, focus }) =>
  `For ${company}, prioritize fundamentals: aptitude speed, OOP, DBMS, SQL, OS, and basic DSA patterns (arrays, strings, hashmaps, stacks, queues, trees). Practice 90-120 minute mocks and review mistakes by category. In interviews, speak in a structured flow: problem understanding -> approach -> complexity -> edge cases. Keep 2 HR stories (conflict and failure-learning) ready. ${focus}`;

const makeExp = (s, idx) => ({
  company: s.company,
  role: s.role,
  year: s.year,
  roundType: s.roundType,
  offerReceived: s.offerReceived,
  ctcOffered: s.offerReceived ? s.ctcOffered : '',
  narrative: buildNarrativeBatch3({
    company: s.company,
    role: s.role,
    year: s.year,
    city: s.city,
    platform: s.platform,
    testDuration: s.testDuration,
    prepWindow: s.prepWindow,
    roundType: s.roundType,
    q1: s.q1,
    q2: s.q2,
    projectAngle: s.projectAngle,
    behaviorMoment: s.behaviorMoment,
    resultLine: s.resultLine,
  }),
  preparationTips: buildTipsBatch3({ company: s.company, focus: s.tipFocus }),
  extractedTags: {
    topics: s.topics,
    keywords: s.keywords,
    difficulty: s.difficulty,
    autoTagged: false,
  },
  embeddingStatus: 'pending',
  upvotes: 5 + (idx % 26),
  isVerified: idx % 10 < 7,
  views: 28 + ((idx * 9) % 170),
});

const batch3Specs = [
  { company: 'Cognizant', role: 'GenC', year: 2024, roundType: 'aptitude', offerReceived: true, ctcOffered: '4.0 LPA', city: 'Vijayawada', platform: 'Cognizant Superset', testDuration: '95-minute', prepWindow: '5 weeks', q1: 'find duplicate elements in an array', q2: 'SQL second highest salary query', projectAngle: 'API response handling and validation', behaviorMoment: 'the interviewer asked me to summarize my answer in 30 seconds, which improved my clarity', resultLine: 'I received the GenC offer in the final list.', tipFocus: 'Do daily aptitude timing drills; Cognizant cutoffs are often speed-driven.', topics: ['Aptitude', 'Quantitative', 'Reasoning', 'SQL', 'Communication'], keywords: ['Superset', 'second highest salary', 'array duplicate', 'sectional timing', 'cutoff'], difficulty: 2 },
  { company: 'Cognizant', role: 'GenC Elevate', year: 2024, roundType: 'coding', offerReceived: true, ctcOffered: '6.5 LPA', city: 'Hyderabad', platform: 'HackerRank', testDuration: '120-minute', prepWindow: '8 weeks', q1: 'LRU cache design with hashmap + DLL', q2: 'minimum window substring', projectAngle: 'backend logging and exception flow', behaviorMoment: 'I initially proposed brute force, then optimized after discussing constraints', resultLine: 'I cleared Elevate after technical follow-up.', tipFocus: 'Practice LRU, sliding window, and clean complexity explanation.', topics: ['DSA', 'LRU Cache', 'Strings', 'Algorithms', 'Problem Solving'], keywords: ['LRU', 'minimum window', 'hashmap', 'DLL', 'optimization'], difficulty: 4 },
  { company: 'Cognizant', role: 'GenC', year: 2023, roundType: 'technical', offerReceived: false, ctcOffered: '4.0 LPA', city: 'Chennai virtual', platform: 'Superset', testDuration: '90-minute', prepWindow: '4 weeks', q1: 'difference between process and thread', q2: 'normalization up to 3NF', projectAngle: 'database schema choices in project', behaviorMoment: 'I over-explained one answer and ran short on later follow-ups', resultLine: 'I missed the final shortlist in this cycle.', tipFocus: 'Keep technical answers concise: definition + example + tradeoff.', topics: ['OS', 'DBMS', 'SQL', 'OOP', 'Communication'], keywords: ['process thread', '3NF', 'schema', 'follow-up', 'shortlist'], difficulty: 2 },
  { company: 'Cognizant', role: 'GenC', year: 2022, roundType: 'hr', offerReceived: true, ctcOffered: '3.9 LPA', city: 'Bengaluru', platform: 'Superset', testDuration: '85-minute', prepWindow: '4 weeks', q1: 'tell me about yourself', q2: 'why Cognizant and relocation readiness', projectAngle: 'team collaboration in capstone', behaviorMoment: 'I gave one genuine failure story with corrective action', resultLine: 'HR round went smooth and I got selected.', tipFocus: 'Use STAR format; avoid generic motivation lines.', topics: ['HR', 'Behavioral', 'Communication', 'Teamwork', 'Leadership'], keywords: ['self intro', 'relocation', 'failure story', 'STAR', 'HR'], difficulty: 2 },
  { company: 'Cognizant', role: 'GenC Next', year: 2024, roundType: 'technical', offerReceived: null, ctcOffered: '7.2 LPA', city: 'Pune', platform: 'HackerEarth', testDuration: '115-minute', prepWindow: '9 weeks', q1: 'Dijkstra shortest path', q2: 'design REST API for attendance workflow', projectAngle: 'API versioning in mini project', behaviorMoment: 'panel asked why Dijkstra over BFS and I explained weighted edges clearly', resultLine: 'I chose not to disclose final result publicly.', tipFocus: 'Learn BFS vs Dijkstra decision logic with examples.', topics: ['Graphs', 'API Design', 'Algorithms', 'DSA', 'SQL'], keywords: ['Dijkstra', 'weighted graph', 'REST API', 'versioning', 'BFS'], difficulty: 4 },
  { company: 'Cognizant', role: 'GenC', year: 2021, roundType: 'aptitude', offerReceived: false, ctcOffered: '3.6 LPA', city: 'Virtual', platform: 'Superset', testDuration: '90-minute', prepWindow: '3 weeks', q1: 'time and work puzzle', q2: 'logical seating arrangement', projectAngle: 'n/a', behaviorMoment: 'I got stuck on one reasoning set and lost sectional balance', resultLine: 'I did not clear OA cutoff.', tipFocus: 'Skip hard puzzles early and return later.', topics: ['Aptitude', 'Quantitative', 'Reasoning', 'Verbal', 'Problem Solving'], keywords: ['time and work', 'seating arrangement', 'sectional cutoff', 'OA', 'speed'], difficulty: 1 },
  { company: 'Cognizant', role: 'GenC', year: 2024, roundType: 'technical', offerReceived: true, ctcOffered: '4.0 LPA', city: 'Vijayawada', platform: 'Superset', testDuration: '95-minute', prepWindow: '5 weeks', q1: 'valid parentheses using stack', q2: 'difference between where and having', projectAngle: 'query optimization in MongoDB vs SQL', behaviorMoment: 'interviewer appreciated that I asked constraints before coding', resultLine: 'I got selected after final technical validation.', tipFocus: 'Practice stack basics and SQL aggregation conditions.', topics: ['Stack', 'SQL', 'DBMS', 'DSA', 'Communication'], keywords: ['valid parentheses', 'where vs having', 'constraints', 'aggregation', 'selection'], difficulty: 2 },
  { company: 'Cognizant', role: 'GenC Elevate', year: 2023, roundType: 'coding', offerReceived: false, ctcOffered: '6.2 LPA', city: 'Hyderabad', platform: 'HackerRank', testDuration: '120-minute', prepWindow: '8 weeks', q1: 'top-k frequent elements', q2: 'merge overlapping intervals', projectAngle: 'performance profiling', behaviorMoment: 'I passed sample tests but missed one hidden edge case', resultLine: 'I could not clear Elevate coding cutoff.', tipFocus: 'Always maintain an edge-case checklist for arrays and intervals.', topics: ['Heaps', 'Arrays', 'Sorting', 'Algorithms', 'Problem Solving'], keywords: ['top k', 'interval merge', 'hidden test', 'edge case', 'cutoff'], difficulty: 3 },
  { company: 'Cognizant', role: 'GenC', year: 2024, roundType: 'hr', offerReceived: true, ctcOffered: '4.0 LPA', city: 'Vijayawada', platform: 'Superset', testDuration: '85-minute', prepWindow: '4 weeks', q1: 'handling disagreements in project team', q2: 'career goals for first 2 years', projectAngle: 'sprint planning and bug triage', behaviorMoment: 'I shared a real conflict-resolution story from hackathon finals', resultLine: 'Offer was rolled out in one week.', tipFocus: 'Keep one conflict and one ownership story ready.', topics: ['HR', 'Behavioral', 'Teamwork', 'Communication', 'Project Management'], keywords: ['disagreement', 'career goals', 'conflict resolution', 'ownership', 'offer'], difficulty: 2 },
  { company: 'Cognizant', role: 'Programmer Analyst Trainee', year: 2022, roundType: 'technical', offerReceived: true, ctcOffered: '4.2 LPA', city: 'Chennai', platform: 'Superset', testDuration: '100-minute', prepWindow: '6 weeks', q1: 'ACID properties with example', q2: 'encapsulation and abstraction difference', projectAngle: 'transaction rollback handling', behaviorMoment: 'panel asked for practical examples and I used payment workflow scenario', resultLine: 'I cleared the PAT technical round and got selected.', tipFocus: 'Pair every definition with one practical scenario.', topics: ['DBMS', 'OOP', 'SQL', 'Technical', 'Communication'], keywords: ['ACID', 'encapsulation', 'abstraction', 'transaction rollback', 'PAT'], difficulty: 2 },
  { company: 'Cognizant', role: 'GenC Next', year: 2024, roundType: 'system_design', offerReceived: true, ctcOffered: '7.4 LPA', city: 'Bengaluru', platform: 'HackerEarth', testDuration: '110-minute', prepWindow: '10 weeks', q1: 'design notification system for 1M users', q2: 'idempotent API for retry-safe operations', projectAngle: 'queue-based async jobs', behaviorMoment: 'I added retry plus dead-letter queue after interviewer prompt', resultLine: 'I received Next role offer.', tipFocus: 'In design rounds, include failure paths and retry strategy.', topics: ['System Design', 'Distributed Systems', 'API Design', 'Kafka', 'Redis'], keywords: ['notification system', 'idempotency', 'dead-letter', 'retry', 'async jobs'], difficulty: 4 },
  { company: 'Cognizant', role: 'GenC', year: 2023, roundType: 'aptitude', offerReceived: true, ctcOffered: '3.9 LPA', city: 'Vijayawada', platform: 'Superset', testDuration: '90-minute', prepWindow: '5 weeks', q1: 'profit and loss set', q2: 'blood relations and coding-decoding', projectAngle: 'n/a', behaviorMoment: 'I used elimination strategy for verbal to save time', resultLine: 'OA cleared and later final offer received.', tipFocus: 'Aptitude speed drills improve shortlist probability significantly.', topics: ['Aptitude', 'Quantitative', 'Reasoning', 'Verbal', 'Communication'], keywords: ['profit loss', 'blood relations', 'elimination', 'verbal', 'shortlist'], difficulty: 2 },
  { company: 'Cognizant', role: 'GenC', year: 2024, roundType: 'technical', offerReceived: null, ctcOffered: '4.0 LPA', city: 'Hyderabad', platform: 'Superset', testDuration: '95-minute', prepWindow: '5 weeks', q1: 'binary search on sorted array', q2: 'left join vs inner join', projectAngle: 'search endpoint optimization', behaviorMoment: 'I corrected one SQL syntax mistake quickly and moved on', resultLine: 'I did not disclose final outcome.', tipFocus: 'Revise SQL joins and binary search edge conditions.', topics: ['Searching', 'SQL', 'DBMS', 'Arrays', 'Problem Solving'], keywords: ['binary search', 'left join', 'inner join', 'syntax fix', 'optimization'], difficulty: 2 },
  { company: 'Cognizant', role: 'GenC Elevate', year: 2022, roundType: 'coding', offerReceived: true, ctcOffered: '6.4 LPA', city: 'Pune', platform: 'HackerRank', testDuration: '120-minute', prepWindow: '9 weeks', q1: 'longest substring without repeating chars', q2: 'coin change minimum coins', projectAngle: 'time complexity tradeoffs', behaviorMoment: 'I wrote test cases first and interviewer appreciated that habit', resultLine: 'Elevate offer confirmed.', tipFocus: 'Practice strings + DP combo problems under strict timer.', topics: ['Strings', 'Dynamic Programming', 'Algorithms', 'DSA', 'Testing'], keywords: ['longest substring', 'coin change', 'test cases', 'DP', 'timer'], difficulty: 4 },
  { company: 'Cognizant', role: 'Programmer Analyst Trainee', year: 2021, roundType: 'hr', offerReceived: false, ctcOffered: '3.8 LPA', city: 'Virtual', platform: 'Superset', testDuration: '85-minute', prepWindow: '3 weeks', q1: 'why should we hire you', q2: 'how do you handle repeated failures', projectAngle: 'n/a', behaviorMoment: 'my answers sounded generic without concrete project examples', resultLine: 'I was not selected in final HR filter.', tipFocus: 'Use examples with measurable outcomes, not abstract claims.', topics: ['HR', 'Behavioral', 'Communication', 'Leadership', 'Teamwork'], keywords: ['why hire', 'failure', 'generic answers', 'HR filter', 'examples'], difficulty: 2 },
  { company: 'Cognizant', role: 'GenC', year: 2024, roundType: 'technical', offerReceived: true, ctcOffered: '4.1 LPA', city: 'Vijayawada', platform: 'Superset', testDuration: '95-minute', prepWindow: '6 weeks', q1: 'reverse linked list', q2: 'difference between delete, truncate, drop', projectAngle: 'CRUD APIs with validation', behaviorMoment: 'I used table-style comparison to answer DBMS commands clearly', resultLine: 'I got selected and completed document verification.', tipFocus: 'Keep quick comparison tables in memory for DBMS commands.', topics: ['Linked Lists', 'SQL', 'DBMS', 'API Design', 'Communication'], keywords: ['reverse linked list', 'delete truncate drop', 'CRUD', 'validation', 'verification'], difficulty: 2 },
  { company: 'Cognizant', role: 'GenC', year: 2023, roundType: 'managerial', offerReceived: true, ctcOffered: '4.0 LPA', city: 'Chennai', platform: 'Superset', testDuration: '90-minute', prepWindow: '5 weeks', q1: 'handling missed sprint deadlines', q2: 'prioritization under conflicting tasks', projectAngle: 'sprint planning', behaviorMoment: 'the manager asked me to choose between quality and deadline and justify tradeoff', resultLine: 'Managerial round cleared and offer issued.', tipFocus: 'Prepare prioritization frameworks with real project examples.', topics: ['Managerial', 'Project Management', 'Leadership', 'Communication', 'Teamwork'], keywords: ['prioritization', 'deadline', 'quality tradeoff', 'managerial round', 'sprint'], difficulty: 3 },
  { company: 'Cognizant', role: 'GenC Next', year: 2024, roundType: 'system_design', offerReceived: false, ctcOffered: '7.3 LPA', city: 'Bengaluru', platform: 'HackerEarth', testDuration: '115-minute', prepWindow: '10 weeks', q1: 'design URL shortener', q2: 'cache invalidation strategy', projectAngle: 'short-link analytics', behaviorMoment: 'I covered happy path well but weak on scale partitioning details', resultLine: 'I did not clear final Next design bar.', tipFocus: 'Include sharding and read-write scaling in design answers.', topics: ['System Design', 'Redis', 'Distributed Systems', 'API Design', 'DBMS'], keywords: ['URL shortener', 'cache invalidation', 'sharding', 'analytics', 'design bar'], difficulty: 4 },
  { company: 'Cognizant', role: 'GenC', year: 2022, roundType: 'technical', offerReceived: true, ctcOffered: '4.0 LPA', city: 'Vijayawada', platform: 'Superset', testDuration: '95-minute', prepWindow: '5 weeks', q1: 'anagram check using hashmap', q2: 'deadlock conditions', projectAngle: 'thread-safe logging', behaviorMoment: 'interviewer interrupted mid-answer to test confidence; I resumed with clear points', resultLine: 'I got selected in final technical list.', tipFocus: 'Practice OS definitions with one practical example each.', topics: ['Strings', 'OS', 'Hashing', 'Technical', 'Communication'], keywords: ['anagram', 'deadlock', 'confidence', 'hashmap', 'thread-safe'], difficulty: 2 },
  { company: 'Cognizant', role: 'Programmer Analyst Trainee', year: 2024, roundType: 'hr', offerReceived: null, ctcOffered: '4.1 LPA', city: 'Hyderabad', platform: 'Superset', testDuration: '85-minute', prepWindow: '4 weeks', q1: 'strength and weakness', q2: 'team conflict resolution', projectAngle: 'bug triage ownership', behaviorMoment: 'I admitted one communication mistake and explained corrective steps', resultLine: 'Final status was kept private.', tipFocus: 'Honest weakness + corrective plan works better than perfection claims.', topics: ['HR', 'Behavioral', 'Teamwork', 'Communication', 'Leadership'], keywords: ['strength weakness', 'conflict', 'corrective action', 'ownership', 'private status'], difficulty: 2 },
  { company: 'Cognizant', role: 'GenC', year: 2021, roundType: 'aptitude', offerReceived: true, ctcOffered: '3.7 LPA', city: 'Virtual', platform: 'Superset', testDuration: '90-minute', prepWindow: '4 weeks', q1: 'percentages and ratio', q2: 'direction sense puzzle', projectAngle: 'n/a', behaviorMoment: 'I used rough-sheet checkpoints every 20 minutes', resultLine: 'I cleared OA and later received offer.', tipFocus: 'Checkpoint strategy avoids panic near section end.', topics: ['Aptitude', 'Quantitative', 'Reasoning', 'Verbal', 'Problem Solving'], keywords: ['ratio', 'direction sense', 'checkpoint', 'section end', 'OA clear'], difficulty: 1 },
  { company: 'Cognizant', role: 'GenC Elevate', year: 2023, roundType: 'coding', offerReceived: true, ctcOffered: '6.3 LPA', city: 'Pune', platform: 'HackerRank', testDuration: '120-minute', prepWindow: '8 weeks', q1: 'kth smallest in sorted matrix', q2: 'topological sort for dependencies', projectAngle: 'dependency graph in deployment', behaviorMoment: 'I explained heap vs binary-search-on-answer tradeoff', resultLine: 'I was selected for Elevate role.', tipFocus: 'Learn heap and graph scheduling patterns deeply.', topics: ['Matrix', 'Heaps', 'Graphs', 'Algorithms', 'DSA'], keywords: ['kth smallest', 'topological sort', 'dependency graph', 'heap', 'tradeoff'], difficulty: 4 },
  { company: 'Cognizant', role: 'GenC', year: 2024, roundType: 'group_discussion', offerReceived: false, ctcOffered: '4.0 LPA', city: 'Campus panel room', platform: 'Superset', testDuration: '80-minute', prepWindow: '3 weeks', q1: 'AI replacing entry-level jobs', q2: 'remote work vs office productivity', projectAngle: 'n/a', behaviorMoment: 'I had good points but interrupted others once, which likely hurt evaluation', resultLine: 'I was not shortlisted after GD.', tipFocus: 'In GD, balanced speaking and listening matter more than volume.', topics: ['Group Discussion', 'Communication', 'Behavioral', 'Leadership', 'Teamwork'], keywords: ['AI jobs', 'remote work', 'GD etiquette', 'interruptions', 'evaluation'], difficulty: 2 },
  { company: 'Cognizant', role: 'GenC', year: 2022, roundType: 'technical', offerReceived: true, ctcOffered: '3.9 LPA', city: 'Chennai', platform: 'Superset', testDuration: '100-minute', prepWindow: '6 weeks', q1: 'binary tree level order traversal', q2: 'indexing and query plan basics', projectAngle: 'read-heavy API optimization', behaviorMoment: 'I wrote BFS first, then explained memory complexity clearly', resultLine: 'I cleared technical and got final offer.', tipFocus: 'Practice tree traversals with complexity explanation.', topics: ['Binary Trees', 'BFS', 'SQL', 'DBMS', 'Algorithms'], keywords: ['level order', 'indexing', 'query plan', 'read-heavy', 'BFS'], difficulty: 3 },
  { company: 'Cognizant', role: 'GenC', year: 2024, roundType: 'technical', offerReceived: true, ctcOffered: '4.1 LPA', city: 'Hyderabad', platform: 'Superset', testDuration: '95-minute', prepWindow: '6 weeks', q1: 'first non-repeating character in string', q2: 'difference between clustered and non-clustered index', projectAngle: 'search and indexing strategy in project backend', behaviorMoment: 'I explained brute force first and then optimized using hashmap with clear complexity comparison', resultLine: 'I cleared technical and received the final offer.', tipFocus: 'Practice string hashing and SQL indexing concepts with examples.', topics: ['Strings', 'SQL', 'DBMS', 'DSA', 'Problem Solving'], keywords: ['non-repeating char', 'clustered index', 'hashmap', 'complexity', 'technical clear'], difficulty: 3 },

  { company: 'HCL', role: 'Graduate Engineer Trainee', year: 2024, roundType: 'aptitude', offerReceived: true, ctcOffered: '3.8 LPA', city: 'Vijayawada', platform: 'HCL Assessment Portal', testDuration: '90-minute', prepWindow: '4 weeks', q1: 'time-speed-distance set', q2: 'series completion and syllogisms', projectAngle: 'n/a', behaviorMoment: 'I prioritized easy verbal first and secured a safer sectional score', resultLine: 'I got shortlisted and later received offer.', tipFocus: 'Section-order strategy can improve total score significantly.', topics: ['Aptitude', 'Quantitative', 'Reasoning', 'Verbal', 'Problem Solving'], keywords: ['TSD', 'series', 'syllogism', 'sectional score', 'shortlist'], difficulty: 2 },
  { company: 'HCL', role: 'Software Engineer', year: 2024, roundType: 'technical', offerReceived: true, ctcOffered: '4.2 LPA', city: 'Noida virtual', platform: 'HackerRank', testDuration: '105-minute', prepWindow: '7 weeks', q1: 'two-sum and variation constraints', q2: 'difference between TCP and UDP', projectAngle: 'REST backend with retries', behaviorMoment: 'I validated constraints before coding and avoided rework', resultLine: 'Technical round cleared successfully.', tipFocus: 'Revise networking fundamentals and hashmap problems.', topics: ['DSA', 'Arrays', 'Networking', 'Algorithms', 'Communication'], keywords: ['two-sum', 'TCP', 'UDP', 'constraints', 'rework'], difficulty: 2 },
  { company: 'HCL', role: 'Graduate Engineer Trainee', year: 2023, roundType: 'hr', offerReceived: false, ctcOffered: '3.7 LPA', city: 'Chennai', platform: 'HCL Portal', testDuration: '85-minute', prepWindow: '4 weeks', q1: 'relocation and shift readiness', q2: 'handling difficult teammate', projectAngle: 'sprint retrospective', behaviorMoment: 'I hesitated on shift flexibility and HR probed further', resultLine: 'I did not clear final HR stage.', tipFocus: 'Be clear and consistent on relocation and shifts.', topics: ['HR', 'Behavioral', 'Communication', 'Teamwork', 'Leadership'], keywords: ['relocation', 'shift', 'difficult teammate', 'HR probe', 'consistency'], difficulty: 2 },
  { company: 'HCL', role: 'Software Engineer', year: 2022, roundType: 'coding', offerReceived: true, ctcOffered: '4.5 LPA', city: 'Hyderabad', platform: 'HackerEarth', testDuration: '110-minute', prepWindow: '8 weeks', q1: 'longest common prefix', q2: 'valid sudoku checker', projectAngle: 'input validation strategy', behaviorMoment: 'I caught one matrix-edge bug through dry run before submission', resultLine: 'I got selected in coding-heavy flow.', tipFocus: 'Dry-run matrix and string problems before final submit.', topics: ['Strings', 'Matrix', 'Algorithms', 'Testing', 'Problem Solving'], keywords: ['LCP', 'sudoku', 'edge bug', 'dry run', 'submission'], difficulty: 3 },
  { company: 'HCL', role: 'Graduate Engineer Trainee', year: 2024, roundType: 'technical', offerReceived: null, ctcOffered: '3.8 LPA', city: 'Vijayawada', platform: 'HCL Assessment', testDuration: '95-minute', prepWindow: '5 weeks', q1: 'stack vs queue operations', q2: 'normalization and denormalization', projectAngle: 'schema design for attendance app', behaviorMoment: 'interviewer appreciated concise tabular comparison', resultLine: 'I completed rounds but did not disclose final result.', tipFocus: 'Keep simple, structured comparisons for DS and DBMS.', topics: ['Stack', 'Queue', 'DBMS', 'SQL', 'Communication'], keywords: ['stack queue', 'normalization', 'denormalization', 'schema', 'tabular'], difficulty: 2 },
  { company: 'HCL', role: 'Software Engineer', year: 2021, roundType: 'aptitude', offerReceived: false, ctcOffered: '3.6 LPA', city: 'Virtual', platform: 'HCL Portal', testDuration: '90-minute', prepWindow: '3 weeks', q1: 'profit-loss and simple interest', q2: 'coding-decoding logic set', projectAngle: 'n/a', behaviorMoment: 'I attempted too many guesses in verbal and accuracy dropped', resultLine: 'I did not clear OA this cycle.', tipFocus: 'Avoid blind guesses in verbal; prioritize accuracy.', topics: ['Aptitude', 'Quantitative', 'Reasoning', 'Verbal', 'Problem Solving'], keywords: ['profit loss', 'interest', 'coding-decoding', 'accuracy', 'OA'], difficulty: 1 },
  { company: 'HCL', role: 'Software Engineer', year: 2024, roundType: 'technical', offerReceived: true, ctcOffered: '4.3 LPA', city: 'Noida', platform: 'HackerRank', testDuration: '105-minute', prepWindow: '7 weeks', q1: 'reverse linked list in k groups', q2: 'ACID + isolation levels', projectAngle: 'transaction retry logic', behaviorMoment: 'I started with baseline approach then optimized after discussing complexity', resultLine: 'I got selected post technical panel.', tipFocus: 'Baseline-first then optimize is safer in live interviews.', topics: ['Linked Lists', 'DBMS', 'SQL', 'Algorithms', 'Problem Solving'], keywords: ['k-group reverse', 'ACID', 'isolation', 'baseline', 'optimize'], difficulty: 3 },
  { company: 'HCL', role: 'Graduate Engineer Trainee', year: 2023, roundType: 'hr', offerReceived: true, ctcOffered: '3.8 LPA', city: 'Vijayawada', platform: 'HCL Portal', testDuration: '85-minute', prepWindow: '4 weeks', q1: 'how do you handle feedback', q2: 'one example of leadership in college', projectAngle: 'team coordination in mini project', behaviorMoment: 'I gave a specific example with timeline and measurable improvement', resultLine: 'HR cleared and offer mail arrived quickly.', tipFocus: 'Quantify outcomes in HR stories whenever possible.', topics: ['HR', 'Behavioral', 'Leadership', 'Communication', 'Teamwork'], keywords: ['feedback', 'leadership', 'timeline', 'improvement', 'offer mail'], difficulty: 2 },
  { company: 'HCL', role: 'Software Engineer', year: 2022, roundType: 'coding', offerReceived: true, ctcOffered: '4.4 LPA', city: 'Chennai', platform: 'HackerEarth', testDuration: '110-minute', prepWindow: '8 weeks', q1: 'anagram grouping', q2: 'minimum swaps to sort array', projectAngle: 'data transformation pipeline', behaviorMoment: 'I explained hash-based grouping and complexity cleanly', resultLine: 'Coding round was cleared in one attempt.', tipFocus: 'Focus on hashing + sorting patterns for HCL coding rounds.', topics: ['Strings', 'Arrays', 'Sorting', 'Algorithms', 'DSA'], keywords: ['anagram group', 'minimum swaps', 'hashing', 'complexity', 'coding round'], difficulty: 3 },
  { company: 'HCL', role: 'Software Engineer', year: 2024, roundType: 'technical', offerReceived: false, ctcOffered: '4.2 LPA', city: 'Hyderabad', platform: 'HCL Test Portal', testDuration: '100-minute', prepWindow: '6 weeks', q1: 'difference between threads and async tasks', q2: 'SQL joins with employee tables', projectAngle: 'async API calls and timeout', behaviorMoment: 'I mixed up one concurrency detail and panel pushed on follow-ups', resultLine: 'I missed final technical shortlist.', tipFocus: 'Revise concurrency terminology and practical examples.', topics: ['Concurrency', 'SQL', 'DBMS', 'Technical', 'Communication'], keywords: ['threads', 'async', 'SQL joins', 'timeout', 'follow-up'], difficulty: 3 },
  { company: 'HCL', role: 'Graduate Engineer Trainee', year: 2021, roundType: 'hr', offerReceived: null, ctcOffered: '3.6 LPA', city: 'Virtual', platform: 'HCL Portal', testDuration: '80-minute', prepWindow: '3 weeks', q1: 'why HCL', q2: 'where do you see yourself in 3 years', projectAngle: 'n/a', behaviorMoment: 'I stayed calm despite connection lag and completed answers in structure', resultLine: 'I chose not to share final status.', tipFocus: 'Practice crisp 3-year goal response with learning milestones.', topics: ['HR', 'Behavioral', 'Communication', 'Leadership', 'Project Management'], keywords: ['why HCL', '3 years', 'connection lag', 'learning milestones', 'structured'], difficulty: 1 },
  { company: 'HCL', role: 'Software Engineer', year: 2024, roundType: 'system_design', offerReceived: true, ctcOffered: '4.8 LPA', city: 'Noida', platform: 'HackerRank + Panel', testDuration: '110-minute', prepWindow: '9 weeks', q1: 'design ticket booking API', q2: 'cache + DB consistency approach', projectAngle: 'booking retry handling', behaviorMoment: 'I added optimistic locking after interviewer asked duplicate booking scenario', resultLine: 'I cleared design round and got final offer.', tipFocus: 'In booking designs, discuss locking and idempotency clearly.', topics: ['System Design', 'API Design', 'Redis', 'DBMS', 'Distributed Systems'], keywords: ['ticket booking', 'optimistic locking', 'idempotency', 'consistency', 'duplicate booking'], difficulty: 4 },
  { company: 'HCL', role: 'Graduate Engineer Trainee', year: 2023, roundType: 'aptitude', offerReceived: true, ctcOffered: '3.8 LPA', city: 'Vijayawada', platform: 'HCL Assessment', testDuration: '90-minute', prepWindow: '5 weeks', q1: 'ratio proportion and percentages', q2: 'statement-assumption reasoning', projectAngle: 'n/a', behaviorMoment: 'I solved quantitative first and saved reasoning for later', resultLine: 'I crossed cutoff and moved to interviews.', tipFocus: 'Pick section order based on your strengths.', topics: ['Aptitude', 'Quantitative', 'Reasoning', 'Verbal', 'Problem Solving'], keywords: ['ratio', 'percentages', 'statement assumption', 'section order', 'cutoff'], difficulty: 2 },
  { company: 'HCL', role: 'Software Engineer', year: 2022, roundType: 'technical', offerReceived: true, ctcOffered: '4.3 LPA', city: 'Chennai', platform: 'HackerEarth', testDuration: '105-minute', prepWindow: '7 weeks', q1: 'binary tree zigzag traversal', q2: 'difference between abstraction and encapsulation', projectAngle: 'service-layer architecture', behaviorMoment: 'I drew traversal flow and explained memory complexity neatly', resultLine: 'Technical panel gave positive feedback and selected me.', tipFocus: 'Draw tree traversal flow to avoid coding confusion.', topics: ['Binary Trees', 'OOP', 'Algorithms', 'DSA', 'Communication'], keywords: ['zigzag traversal', 'abstraction', 'encapsulation', 'memory complexity', 'panel'], difficulty: 3 },
  { company: 'HCL', role: 'Software Engineer', year: 2024, roundType: 'coding', offerReceived: false, ctcOffered: '4.5 LPA', city: 'Hyderabad', platform: 'HackerRank', testDuration: '110-minute', prepWindow: '8 weeks', q1: 'word break using DP', q2: 'first unique char in stream', projectAngle: 'token processing pipeline', behaviorMoment: 'I reached correct DP state but code had boundary bug', resultLine: 'I did not clear coding final threshold.', tipFocus: 'Write boundary conditions explicitly before coding DP.', topics: ['Dynamic Programming', 'Strings', 'Algorithms', 'DSA', 'Testing'], keywords: ['word break', 'unique char stream', 'boundary bug', 'DP state', 'threshold'], difficulty: 4 },
  { company: 'HCL', role: 'Graduate Engineer Trainee', year: 2021, roundType: 'technical', offerReceived: true, ctcOffered: '3.7 LPA', city: 'Virtual', platform: 'HCL Portal', testDuration: '95-minute', prepWindow: '4 weeks', q1: 'HTTP vs HTTPS', q2: 'indexing impact in SQL queries', projectAngle: 'API latency debugging', behaviorMoment: 'I used simple analogies and interviewer said explanation was clear', resultLine: 'I was selected in final technical list.', tipFocus: 'Networking + SQL basics are frequently asked together.', topics: ['Networking', 'SQL', 'DBMS', 'Technical', 'Communication'], keywords: ['HTTP', 'HTTPS', 'indexing', 'latency', 'analogy'], difficulty: 2 },
  { company: 'HCL', role: 'Software Engineer', year: 2024, roundType: 'technical', offerReceived: null, ctcOffered: '4.2 LPA', city: 'Noida', platform: 'HCL Assessment', testDuration: '100-minute', prepWindow: '6 weeks', q1: 'implement queue using stacks', q2: 'normal forms with example', projectAngle: 'data ingestion queue', behaviorMoment: 'I discussed amortized complexity and that improved confidence', resultLine: 'I kept final result private.', tipFocus: 'Practice DS implementation questions with complexity notes.', topics: ['Queue', 'Stack', 'DBMS', 'Algorithms', 'Problem Solving'], keywords: ['queue using stacks', 'normal forms', 'amortized complexity', 'ingestion', 'private'], difficulty: 3 },
  { company: 'HCL', role: 'Graduate Engineer Trainee', year: 2023, roundType: 'hr', offerReceived: true, ctcOffered: '3.8 LPA', city: 'Vijayawada', platform: 'HCL Portal', testDuration: '85-minute', prepWindow: '4 weeks', q1: 'how do you handle pressure', q2: 'example of teamwork under deadlines', projectAngle: 'hackathon sprint delivery', behaviorMoment: 'I gave a timeline-based story and highlighted shared ownership', resultLine: 'HR approved and offer was released.', tipFocus: 'Timeline-based storytelling sounds more credible in HR rounds.', topics: ['HR', 'Behavioral', 'Teamwork', 'Communication', 'Leadership'], keywords: ['pressure', 'deadline', 'timeline', 'ownership', 'HR approved'], difficulty: 2 },
  { company: 'HCL', role: 'Software Engineer', year: 2022, roundType: 'system_design', offerReceived: false, ctcOffered: '4.6 LPA', city: 'Chennai', platform: 'HackerEarth + Panel', testDuration: '110-minute', prepWindow: '9 weeks', q1: 'design URL shortener', q2: 'database sharding strategy', projectAngle: 'analytics and click tracking', behaviorMoment: 'I handled API flow well but was weak on shard key choice', resultLine: 'I did not clear final design discussion.', tipFocus: 'Practice shard-key selection and read/write scaling tradeoffs.', topics: ['System Design', 'Distributed Systems', 'DBMS', 'API Design', 'Redis'], keywords: ['URL shortener', 'sharding', 'shard key', 'analytics', 'scaling'], difficulty: 4 },
  { company: 'HCL', role: 'Software Engineer', year: 2024, roundType: 'technical', offerReceived: true, ctcOffered: '4.4 LPA', city: 'Hyderabad', platform: 'HackerRank', testDuration: '105-minute', prepWindow: '7 weeks', q1: 'find cycle in linked list', q2: 'explain CAP theorem basic tradeoff', projectAngle: 'distributed cache consistency', behaviorMoment: 'I gave a practical tradeoff example instead of textbook definition', resultLine: 'I got selected after final review.', tipFocus: 'Use real examples for distributed-system concepts.', topics: ['Linked Lists', 'Distributed Systems', 'Algorithms', 'Technical', 'Communication'], keywords: ['cycle detection', 'CAP theorem', 'tradeoff', 'consistency', 'review'], difficulty: 3 },

  { company: 'Accenture', role: 'Associate Software Engineer', year: 2024, roundType: 'aptitude', offerReceived: true, ctcOffered: '4.5 LPA', city: 'Vijayawada', platform: 'Accenture Pymetrics + Coding', testDuration: '100-minute', prepWindow: '5 weeks', q1: 'ratio and percentage DI set', q2: 'basic pseudocode debugging', projectAngle: 'n/a', behaviorMoment: 'I kept strong pacing and completed all sections with review time', resultLine: 'I cleared assessment and received ASE offer.', tipFocus: 'Accenture rounds reward balanced speed across sections.', topics: ['Aptitude', 'Quantitative', 'Reasoning', 'Problem Solving', 'Verbal'], keywords: ['Pymetrics', 'DI', 'pseudocode', 'section pacing', 'ASE'], difficulty: 2 },
  { company: 'Accenture', role: 'Associate Software Engineer', year: 2023, roundType: 'technical', offerReceived: false, ctcOffered: '4.5 LPA', city: 'Hyderabad', platform: 'Accenture Assessment Portal', testDuration: '105-minute', prepWindow: '6 weeks', q1: 'difference between abstraction and polymorphism', q2: 'SQL joins and group by query', projectAngle: 'microservice API integration', behaviorMoment: 'I answered fundamentals well but project-depth answers were shallow', resultLine: 'I was not selected in final panel.', tipFocus: 'Prepare deep project Q&A, not only textbook fundamentals.', topics: ['OOP', 'SQL', 'DBMS', 'Technical', 'API Design'], keywords: ['abstraction', 'polymorphism', 'group by', 'project depth', 'panel'], difficulty: 2 },
  { company: 'Accenture', role: 'Advanced ASE', year: 2024, roundType: 'coding', offerReceived: true, ctcOffered: '6.8 LPA', city: 'Bengaluru', platform: 'HackerRank', testDuration: '120-minute', prepWindow: '9 weeks', q1: 'minimum platform problem using sorting', q2: 'LRU cache operations', projectAngle: 'cache-first backend flow', behaviorMoment: 'I explained both greedy and heap variants before coding final version', resultLine: 'Advanced ASE offer was confirmed.', tipFocus: 'Practice greedy + heap alternatives for scheduling problems.', topics: ['Sorting', 'Heaps', 'LRU Cache', 'Algorithms', 'DSA'], keywords: ['minimum platform', 'greedy', 'heap', 'LRU', 'backend cache'], difficulty: 4 },
  { company: 'Accenture', role: 'Associate Software Engineer', year: 2022, roundType: 'hr', offerReceived: null, ctcOffered: '4.3 LPA', city: 'Virtual', platform: 'Accenture Portal', testDuration: '85-minute', prepWindow: '4 weeks', q1: 'why Accenture and project interests', q2: 'team conflict handling', projectAngle: 'sprint defect triage', behaviorMoment: 'I shared a concise conflict story and highlighted accountability', resultLine: 'I did not disclose final status publicly.', tipFocus: 'Concise, evidence-based HR answers improve interviewer trust.', topics: ['HR', 'Behavioral', 'Teamwork', 'Communication', 'Leadership'], keywords: ['why Accenture', 'conflict', 'accountability', 'defect triage', 'public status'], difficulty: 2 },
  { company: 'Accenture', role: 'Associate Software Engineer', year: 2021, roundType: 'technical', offerReceived: true, ctcOffered: '4.2 LPA', city: 'Virtual', platform: 'Accenture Assessment', testDuration: '100-minute', prepWindow: '5 weeks', q1: 'binary search + edge conditions', q2: 'difference between process and thread', projectAngle: 'API latency troubleshooting', behaviorMoment: 'I wrote quick edge-case list before coding and avoided mistakes', resultLine: 'I was selected and completed onboarding formalities.', tipFocus: 'Edge-case listing before coding prevents avoidable bugs.', topics: ['Searching', 'OS', 'DSA', 'Technical', 'Problem Solving'], keywords: ['binary search', 'edge conditions', 'process thread', 'latency', 'onboarding'], difficulty: 2 },
];

const batch3 = batch3Specs.map((s, i) => makeExp(s, i));

export default batch3;
